### ISSUE TITLE
Update documentation to show and explain all parameters

### ISSUE THREAD

**Issue by makbol** [johnste/finicky#102]
First of all, thank you for bringing us this tremendously useful tool!

Unfortunately I could't find complete documentation on what params I might expect to get in `match` method. From examples it's: `url`, `sourceBundleIdentifier `, `sourceProcessPath `, `keys`... what else? Also there's missing documentation on available methods of `finicky`

**Comment by johnste** [comment]
Good point. I created documentation of the configuration here https://johnste.github.io/finicky-docs/ but I didn't have time to keep it up to date. It's outdated but should hopefully provide you with some more information.

**Comment by johnste** [comment]
Added documentation in [Readme](https://github.com/johnste/finicky#function-parameters)
