### ISSUE TITLE
Ability to open specific browser based on the app launching the URL

### ISSUE THREAD

**Issue by clustor** [johnste/finicky#106]
I realize this might not be feasible but I thought I would check anyway.  I currently use Firefox for personal stuff and Chrome from work related sites. 

Is it possible to launch Chrome when URLs are clicked from work related apps (Slack, Outlook, Powerpoint, Word, etc) and launch Firefox for all other links?

**Comment by johnste** [comment]
Yes, it is possible, check out [advanced usage](https://github.com/johnste/finicky/#advanced-usage-settings).

Use [this tip](https://github.com/johnste/finicky/wiki/Troubleshooting-&-Tips#i-want-to-use-the-sourcebundleidentifier-option-but-i-dont-know-what-bundle-id-to-listen-to) to figure out the bundle identifiers for the apps opening the url and you can write a handler that matches on them.

**Comment by clustor** [comment]
Perfect. thanks.
