### ISSUE TITLE
Allow opening links in the background

### ISSUE THREAD

**Issue by serenium** [johnste/finicky#11]
If Finicky is called to open a link in the background, it should pass this request onto the browser. After a quick hunt through the documentation it looks like the flag responsible for this is `NSWorkspaceLaunchWithoutActivation` in 
`NSWorkspaceLaunchOptions` when calling `openURLs:withAppBundleIdentifier`.

EDIT: it might be nice to allow this to be changed with the API too, for example, revealed to the function in the opts variable, and possibly changed with a flag in the return value.

**Comment by johnste** [comment]
Fixed in v0.4 https://github.com/johnste/finicky/releases/tag/v0.4

Did not add the flag to the opts variable this time around, but will consider it.
