### ISSUE TITLE
SourceBundleIdentifier is null

### ISSUE THREAD

**Issue by clustor** [johnste/finicky#110]
The bundle identifier for KeeWeb (keeweb.info) is null and I get an error every time I click a link from this app. 

`Configuration: TypeError: null is not an object (evaluating 'sourceBundleIdentifier.startsWith')`

I worked around by checking for null but I am curious why sourceBundleIdentifier is null

    {
      match: ({ sourceBundleIdentifier }) =>
        (sourceBundleIdentifier !== null) && sourceBundleIdentifier.startsWith("com.microsoft"),
      browser: "Google Chrome"
    },

$ /usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' /Applications/KeeWeb.app/Contents/Info.plist
net.antelle.keeweb

**Comment by johnste** [comment]
Hi! 

Yes, I can confirm I'm also getting `null` for sourceBundleIdentifier. I don't know why this happens for some apps, I suspect it depends on how the url is activated.

However, I do have a workaround. By adding a rewrite handler that logs all parameters ([which I just added to the wiki](https://github.com/johnste/finicky/wiki/Troubleshooting-&-Tips#i-want-to-see-all-incoming-parameters-to-the-url-handling-functions)) I could see that the (somewhat hidden) sourceProcessPath parameter could identify the source application:

```json
{
  "urlString": "http://test.com/",
  "url": {
    "username": "",
    "host": "test.com",
    "protocol": "http",
    "pathname": "/",
    "search": "",
    "password": "",
    "hash": ""
  },
  "sourceProcessPath": "/Applications/KeeWeb.app/Contents/Frameworks/KeeWeb Helper (Renderer).app/Contents/MacOS/KeeWeb Helper (Renderer)",
  "keys": {
    "command": false,
    "capsLock": false,
    "function": false,
    "option": false,
    "control": false,
    "shift": false
  },
  "sourceBundleIdentifier": null
}
```

So a match function that looks something like this could probably work for you:

```js
match: ({ sourceProcessPath }) => sourceProcessPath.includes("KeeWeb")
```

**Comment by clustor** [comment]
This definitely works if a browser needs to be set explicitly but a user could be running into errored condition with other apps reporting null. 

Would it make sense to launch default browser if "sourceBundleIdentifier" is null with some kind of warning message in the console? 

I don't know how MacOS determines bundle id but it would be great to find out if the OS is giving null and see if that behavior can be fixed.

**Comment by johnste** [comment]
My assumption has been that this happens because of how Finicky / the default browser is activated by the source application. I don't think there are any guarantees that the source bundle id is always available. 

I don't think Finicky should handle the bundle id being null in any special way since it only would play any role if a Finicky user wants to use it _and_ that application doesn't launch the browser in a way where Finicky can read the bundle id.

I suppose one approach that could be taken is for Finicky to try and figure out the bundleId manually based if `sourceProcessPath` is available, but I'm not sure it's worth the effort.

**Comment by clustor** [comment]
Not sure if it's worth the effort. For now, I am happy with my workaround.
