### ISSUE TITLE
Feature request: Support Rambox

### ISSUE THREAD

**Issue by dschuessler** [johnste/finicky#112]
I'd love to see support for Rambox as browser: https://rambox.pro/

**Comment by dschuessler** [comment]
I just took a look into it myself. I registered Rambox in `browsers.swift` and got it to focus when opening a link matching a handler. But it seems, Rambox is currently not capable of opening links from the outside: https://github.com/ramboxapp/community-edition/issues/1500

**Comment by johnste** [comment]
Nothing should be stopping Finicky from using Rambox as a browser, provided it accepts incoming links. I'm going to close this issue since there isn't much I can do about it.
