### ISSUE TITLE
URL Shorteners documentation

### ISSUE THREAD

**Issue by sashkab** [johnste/finicky#117]
From  #79:

> Thanks for telling me. It was mentioned before in the documentation but it was lost when I rewrote it. I'll add it.

I think it was lost yet again.   I didn't find mention of url shorteners in the documentation. 

Also, I was wondering, if there is a way to open any, let's say t.co links in specific browser, **before** expanding them? 

Because adding following to config, doesn't help to open t.co links in the Firefox, and they are always opened in the Safari, which is default browser. 

```js
    handlers: [
        {
            match: finicky.matchHostnames([
                "t.co",
            ]),
            browser: "Firefox"
        },
```

Thanks.

**Comment by johnste** [comment]
Thanks for pointing it out. I added the documentation back [here](https://github.com/johnste/finicky/wiki/Configuration#options) in the wiki where it will hopefully not be lost again. 

If you provide the shortUrlProvider setting in the options you can override it. If you leave out t.co in that list, you can handle those urls like normal ones like in your example.

**Comment by sashkab** [comment]
Thanks! 

This is now resolved. Appreciate quick response!
