### ISSUE TITLE
Browser does not get focus if in another virtual desktop than where url is clicked

### ISSUE THREAD

**Issue by notDavid** [johnste/finicky#118]
Hi there,

FYI bug #82 is happening again since i updated to version v3.0.0 (232).

**Comment by johnste** [comment]
Thanks for the bug report. I'm assuming this regression was caused by the fix for #111.

I'll look in to it!

**Comment by johnste** [comment]
Not able to reproduce this at this point, following the steps described in https://github.com/johnste/finicky/issues/82#issue-512854181

**Comment by notDavid** [comment]
Me neither, in v3.1.3 (254).

So i guess it was somehow fixed either as a side effect to one of the finicky updates above v3.0.0 (232), or in a macOS update 🤷🏼‍♂️ 🙂
