### ISSUE TITLE
Rewriting Zoom links to automatically join

### ISSUE THREAD

**Issue by jeremykanter** [johnste/finicky#121]
Was wondering if anyone could help me configure Zoom links to automatically join in the browser. Basically all I want to do is transform this…

https://us02web.zoom.us/j/12345678901

into this…

https://us02web.zoom.us/wc/12345678901/join

…but I'm not entirely sure how to get that working. Thanks in advance!

**Comment by johnste** [comment]
try this, add as a `rewrite`:
```js
{
	match: "https://us02web.zoom.us/j/*",
	url: ({url}) => ({
		pathname: url.pathname.replace('/j/', '/wc/') + "/join"
	})
}
```

**Comment by jeremykanter** [comment]
Amazing! Thanks for the quick reply!
