### ISSUE TITLE
Console should not use fancy quotes

### ISSUE THREAD

**Issue by pichfl** [johnste/finicky#122]
It's a bit odd that the console uses fancy quotes for debugging output. 

This breaks things like the example configuration, which does render invalid curly quotes in my locale (de-DE).

**Comment by johnste** [comment]
Thanks for the feedback! Not sure why there output is using non-standard characters when printing this output. I've been considering just replacing the example with a link that can be updated separately (i.e. in the wiki), which would avoid this issue.

**Comment by pichfl** [comment]
I create a PR for this, adding a few extra lines to the TextField works 🙂
