### ISSUE TITLE
Display notification for when a handler was triggered 

### ISSUE THREAD

**Issue by pichfl** [johnste/finicky#124]
Showing a system notification if Finicky successfully rerouted a link to anything but the default browser might reduce the magic of the app, but will also help with understanding what's happening. 

As notifications can be configured on the OS level (via System Preferences to be precise), it's not even necessary to provide any UI if people want to disable this.

**Comment by johnste** [comment]
Hm, not entirely sure this is necessary? I haven't seen this feedback before. 

In general, the idea behind Finicky is to stay in the background and just doing it's job. You could trigger notifications with `finicky.notify(title, message)` if you want more information.

**Comment by pichfl** [comment]
Yep, that works fine, must have skipped it on my first read of the API. Closing this.
