### ISSUE TITLE
Focusing behavior when opening link from menu bar app

### ISSUE THREAD

**Issue by uetchy** [johnste/finicky#126]
Thank you for creating a niche but super useful app!
I have a problem with Finicky when opening links from menu bar apps such as Fork, Dropbox.

**expected behaviour**
1. Uses app like Xcode
2. Open menu bar app and click on a link
3. Open link in a web browser keeping its window frontmost.

**actual behaviour**
1. Uses app like Xcode
2. Open menu bar app and click on a link
3. Nothing happened (actually, Finicky opened the link in the web browser but instantly focused back to the previously used app (Xcode))

Technically, can we distinguish whether the link was opened from the menu bar app or not? If so, we can fix this issue.

1. if the link is opened from a menu bar app -> open the link in the web browser
2. otherwise, open the link in the web browser and focus back to the previously used app

## Refs

https://github.com/johnste/finicky/blob/6ac7b97f143579e41904ed486e30e0a17bd0faa7/Finicky/Finicky/AppDescriptor.swift#L37

**Comment by johnste** [comment]
Been attempting to reproduce this as well as #118 but not having any luck – tried with Safari and Chrome in the same as well as different spaces, opening the "What's new in Xcode" link in Xcode and they both show up front and center regardless if they are running or not.

**Comment by uetchy** [comment]
@johnste I forgot to point out that this issue only occurs when `openInBackground` is not set or set to `true`.

When I click on a link item from a popup window in the menu bar app (for example, GitHub notifications in Fork), if `openInBackground` is enabled, the web page is opened silently behind the maximized frontmost app and looks like nothing happened. I initially thought that Finicky didn't handle the link properly.

For now Finicky is working fine with the settings below:

```js
module.exports = {
  defaultBrowser: {
    name: "Safari",
    openInBackground: false,
  },
}
```

**Comment by johnste** [comment]
Ran all my tests not having set `openInBackground` at all to have it fall back to the default behavior which is to open the app in the background only if it hasn't been given focus. 
`self.openInBackground = openInBackground ?? !NSApplication.shared.isActive`

If you wouldn't mind, could you attempt to reproduce this issue again without the `openInBackground` flag set? 

Also, I'm running Big Sur, curious if you are not.

**Comment by uetchy** [comment]
I tried with no `openInBackground`, and it turned out to be a Fork specific issue.

To reproduce:
1. Focus on any app (Xcode, iTerm, etc)
2. Click on Fork icon in menu bar (https://forkapp.io/)
3. Click any GitHub notification item
4. The link will be opened in background

If I recall correctly Dropbox popup window had the same issue (I don't use it anymore so cannot guarantee though)

```
Finicky: v3.1.3 (254)
macOS: 11.1 Big Sur
Xcode: 12.4
```

**Comment by johnste** [comment]
I'm still not able to reproduce this. I installed Fork and added a github account to get the notifications, but Safari is still appearing.

Adding a small clip of me trying to reproduce [https://www.youtube.com/watch?v=7ejj4h3x9DI](https://www.youtube.com/watch?v=7ejj4h3x9DI)

**Comment by uetchy** [comment]
Ok I recorded a clip too: https://youtu.be/MAqvUfl5tBs
It happens when:
- Safari window sits somewhere in background
- Safari window is minimized

**Comment by johnste** [comment]
Hm. What app is getting the focus after the first notification click at around 6 seconds? 

I'll have to look more into focusing behavior and detecting these issues but it will probably be hard to work on until I can figure out a repro.

**Comment by uetchy** [comment]
@johnste It was iTerm but strangely enough, its window was out of focus after clicking the link. Maybe I should have included the entire menu bar. Here is the second shot: https://youtu.be/3Svrrt7zij4

**Comment by johnste** [comment]
Thank you for the new video. The behavior looks very random to me. You're not really doing anything different between the initial few attempts as far as I can tell but it defocuses the iterm window (but not the app)  and opens the link in the background.

I'll try to repro using the same set up. Thanks again!

**Comment by johnste** [comment]
I can't reproduce it.

I have a slight suspicion that your computer is fast enough for finicky to not have received focus before having handled the url. If finicky doesn't have focus it will assume the browser shouldn't be in focus either.

I'm thinking a small delay of a few milliseconds might give finicky enough time to be the app in focus. I will have access to another mac from next week so I could try to reproduce the issue on that one.

**Comment by johnste** [comment]
Published [3.3.0](https://github.com/johnste/finicky/releases/tag/v3.3.0) just now that contains a small delay. If you're still able, would you let me know if it helps with your issue?

**Comment by uetchy** [comment]
@johnste Thank you, I've cloned master and tested it myself and realized that 50ms was not enough to prevent glitching, so I increased it to 100ms and this time it clearly improved.
For minimized windows, however it has no effect no matter how much delay I added.
I have no idea why `NSApplication.shared.isActive` is so unreliable. Maybe we have to look for a better way.

**Comment by johnste** [comment]
Thanks for the troubleshooting! I'll revisit this in a week or so when I have a second set up to test with.

**Comment by johnste** [comment]
Okay, I have a new environment to test in and I can reproduce the issue now  💪

**Comment by johnste** [comment]
I've spent several hours trying to track down a way to figure out if the url being opened would open the app in the background or not.
 
`applicationWillBecomeActive` is activated up to around 70 milliseconds after recieving the url event for me, and the only way around it is to wait.

Another option might be to keep a referenced to the open browser around and activate it if/when we get the activation event, but I'm not sure if it's even feasible.

For now I guess increasing the delay to just above 100 milliseconds is our best option.

**Comment by johnste** [comment]
Pushed a commit c676e5e988656f7d462e6710ac7311fa5d5ed5a9 that increases the delay to 120 ms. For now I'll consider this fixed when the next release is available.

**Comment by johnste** [comment]
Newest release is out now, hopefully this issue is fixed https://github.com/johnste/finicky/releases/tag/v3.4.0

**Comment by uetchy** [comment]
@johnste Thank you! That behavior has been alleviated in the latest version.
