### ISSUE TITLE
http URLs from Tweetbot seem to be re-written to https

### ISSUE THREAD

**Issue by johnjensenish** [johnste/finicky#127]
Repro steps: 
1. Open Tweetbot
2. Find a link to a non-secure URL (i.e. http://) for a domain that does not support `https`; here's an example Tweet https://twitter.com/sullydish/status/1280950273020760068
3. Set the system default browser to Finicky
4. Click the link

Results:
5. Error showing that the page isn't secure because the `https` protocol is trying to be used. Note that if the domain supports https://, then an error message won't occur, so for many domains this won't be a problem.

I was able to repro this bug with a trivial config:
```module.exports = {
  defaultBrowser: "Safari",
};
```

This does not repro if my system's default browser is Safari. If I copy and paste the URL, it works fine. The issue repros whether Finicky opens Chrome or Safari.

I cannot repro this issue in another app (I tested Slack).

<img width="1081" alt="Screen Shot 2020-07-08 at 2 42 14 PM" src="https://user-images.githubusercontent.com/37423111/86973315-409be580-c129-11ea-8356-100b21b448b3.png">

<img width="544" alt="Screen Shot 2020-07-08 at 2 42 17 PM" src="https://user-images.githubusercontent.com/37423111/86973337-48f42080-c129-11ea-8d80-b7ef0bcd73af.png">

**Comment by johnste** [comment]
Hm, not sure what's going on here. If I check the headers for the linked url it should resolve to the https url, so that would cause the issue without Finicky being involved at all, but since you mention it works in Safari I'll have a close look.

![image](https://user-images.githubusercontent.com/886051/89936803-78101d00-dc14-11ea-98ed-0e0283ad9466.png)

**Comment by johnjensenish** [comment]
If you have the Tweetbot app for macOS, I found that the the URL scheme for that particular tweet is tweetbot://sullydish/status/1280950273020760068

I can still reproduce the issue with that link.

I don't really any insight into the HTTP headers, but I see that https://urlex.org/ does expand the URL to have a plain http protocol. So do the browsers themselves. Maybe there is a different technique for resolving the URL?

Another idea is to pass along the original URL to the web browser. I think that would also address another issue I experienced #84

**Comment by johnste** [comment]
Okay, seems like t.co returns different responses when triggering the link.

If I use a browser, the response data is HTTP 200 OK with a simple script to replace the page url. This uses the original http link.

```html
<head><meta name="referrer" content="always"><noscript><META http-equiv="refresh" content="0;URL=http://dish.andrewsullivan.com/awards/mmxiv/yglesias-award/"></noscript><title>http://dish.andrewsullivan.com/awards/mmxiv/yglesias-award/</title></head><script>window.opener = null; location.replace("http:\/\/dish.andrewsullivan.com\/awards\/mmxiv\/yglesias-award\/")</script>
``` 

If I curl the t.co url directly it returns a HTTP 301 Moved Permanently with the https url instead.

**Comment by johnste** [comment]
I tried filing a bug report with Twitter for this issue, but I don't count on anything happening. For now disabling t.co might be an option.

**Comment by johnste** [comment]
Outside of sending custom headers and parsing the html coming back we won't be able to get this to work I think – the problem lies with t.co and not finicky. https://urlex.org seems to be able to handle this redirect somehow, but no other short url expanders I've tried did.

Closing for now.

**Comment by johnjensenish** [comment]
Since this is the URL shortening service used by Twitter, it can be hard to avoid. :(

Hmm, how about sending the non-expanded URL to the browser? i.e. tell the browser to go to the `t.co` URL so it can do correct forwarding? Is there a good reason to send the expanded URL to the browser?

I can see a design where the URL is expanded to evaluate Finicky rules, but the original URL is passed off to the target browser. This would also avoid some edge cases where a URL can be expanded differently based on cookies or authorization. In the end, the target browser will always have more user context and capabilities, so I think this design might make sense. Just my two cents as a developer :)

Thanks for your attention on the issue. Most links I see on Twitter end up being https, so it's not the end of the world.

**Comment by johnste** [comment]
The two reasons for sending the expanded URL to the browsers are
1. To avoid another redirection delay resolving the short URL to the expanded one.
2. Finicky might have rewritten the URL, so using the orignal URL would disregard any change.

I think, for now, the best option is probably to disable `t.co` expansion (with the new urlShorteners callback in [3.2.0](https://github.com/johnste/finicky/releases/tag/v3.2.0) if this is an issue.
