### ISSUE TITLE
Ability to append/remove from default urlShorteners

### ISSUE THREAD

**Issue by vincer** [johnste/finicky#129]
You can only fully override `urlShorteners` currently so if you're just looking to add (or remove) one, you need to find the default list and copy/paste it into your config. This is both a bit onerous and additionally means that you won't get future updates to the default list.

My own example is that I want to add `applications.zoom.us` as an url shortener but not change the defaults.

Maybe `urlShorteners` can optionally take a method that has the defaults as an argument:
```
({defaultShorteners}) => defaultShorteners.concat(["applications.zoom.us"])
```

**Comment by johnste** [comment]
Released in [3.2.0](https://github.com/johnste/finicky/releases/tag/v3.2.0)
