### ISSUE TITLE
I've hidden the menu bar icon, how do I get it back?

### ISSUE THREAD

**Issue by edmundho** [johnste/finicky#130]
Additionally, how do I reload the configuration without it? How do I reboot Finicky (other than rebooting my computer?). I can't find it anywhere now that the menu bar is gone, and the process number keeps changing! Thanks.

**Comment by johnste** [comment]
Can you post your configuration? Finicky should only hide the menu bar icon if you set the [hideIcon](https://github.com/johnste/finicky/wiki/Configuration#options) option to do so. 

Finicky will reload the configuration any time the file is changed.

**Comment by edmundho** [comment]
```
// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",      
  handlers: [
    {
      match: /^https?:\/\/google\.com\/.*$/,
      browser: "Google Chrome"
    },
    {
      match: /^https?:\/\/localhost.*$/,
      browser: "Firefox Developer Edition"
    }
  ]
}
```
i removed the hideIcon property and it didn't seem to reload

**Comment by johnste** [comment]
Sorry, not sure how I can help you without more information. It seems to be an issue only happening on you machine. Are you using any app like [Bartender](https://www.macbartender.com/) or other apps to change how the mac menu works?
