### ISSUE TITLE
Possible to use with nativefier apps?

### ISSUE THREAD

**Issue by breathe** [johnste/finicky#131]
I'm overwhelmed with browser tabs.

I started using an app called nativefier -- https://github.com/jiahaog/nativefier -- to create wrapper apps around specific webpages -- the generated wrapped uses chromium/electron ...  

Is it possible to get finicky to load such apps in response to url's rather than just browsers?

**Comment by breathe** [comment]
I've created a nativitier app for JIRA -- and tried to use it

```
    {
      match: /^https?:\/\/itsacheckmate\.atlassian\.net\/.*$/,
      browser: "/Applications/jira-devops.app",
    },
```

finicky launches the jira-devops.app -- but doesn't navigate to the correct url ...

**Comment by breathe** [comment]
I guess that this issue in nativifier blocks this ... -- 

https://github.com/jiahaog/nativefier/issues/405

**Comment by johnste** [comment]
Not much we can do about this until nativifier supports it. Feel free to comment or open a new issue if there are updates!
