### ISSUE TITLE
Where to store configuration file

### ISSUE THREAD

**Issue by BillS11** [johnste/finicky#132]
Hi, apologies for the very basic question.
Where do I actually store the .finicky.js file? What exactly is “home directory” as stated in the readme?
I was also unable to create a filename with a period at the start of the filename. What is the method for creating this file? 

(I know to use the kickstart link for the content of the file itself)

Thanks in advance.

**Comment by johnste** [comment]
You can find the home folder in Finder by pressing `command`+`shift`+`h` 

Then, you can press `command`+`shift`+`.` to be able to see all files in that folder. Now you should be able to rename or save files with the preceding dot. You should see a warning when you do this but it should let to you continue. 
![image](https://user-images.githubusercontent.com/886051/90128316-ff6da580-dd66-11ea-95a2-47a4c4fcaae9.png)

The keyboard shortcuts should also work in the save dialog of a text editor.

**Comment by johnste** [comment]
On another note, I'm considering also accepting a configuration file without the preceding dot to help users who aren't used to use them.

**Comment by BillS11** [comment]
Awesome, this worked! Thanks for the prompt response :)
