### ISSUE TITLE
Configuration: Error: Expected "module.exports.handlers[6].browser

### ISSUE THREAD

**Issue by rzuritamilla** [johnste/finicky#136]
hi there,

I am new to finicky. Have the latest version 3.1.1. and added the below code to my config file to remove trackers (copied from the documentation)

{
  match: ({ url }) => (url.search.includes("utm_")),
  url({ url }) {
    const search = url.search.split('&').filter(part => !part.startsWith("utm_"));
    return {
      ...url,
      search: search.join('&')
    }
  }
}

but finicky says:

2020-09-20 - Configuration: Error: Expected "module.exports.handlers[6].browser" to be function(options), {
  "name": "string",
  "appType": "appPath, appName or bundleId",
  "openInBackground": "boolean",
  "profile": "string"
}, string or null or array

what am i doing wrong? indentation? error in the code above?

Thanks,
Raul

**Comment by johnste** [comment]
Sounds like this might be the same issue as discussed in this issue
<https://github.com/johnste/finicky/issues/135>. Maybe the documentation
isn't clear enough on the differences between rewriting urls and starting
browsers.

**Comment by rzuritamilla** [comment]
ah, I see. I was, indeed, mixing up the option to rewrite urls with the one to start the browsers. Thanks for your prompt reply!
