### ISSUE TITLE
Configuration: Error: Expected an object to validate, but received undefined (path: module.exports.)

### ISSUE THREAD

**Issue by xiaobq** [johnste/finicky#140]
Whenever I changed the config file correctly and save it in my VS Code, most of the time it reports error 
**Configuration: Error: Expected an object to validate, but received undefined (path: module.exports.)**

I can ignore it and it still works.
When I save it again, it may say "reload config successfully."

How can we solve this annoying error message?

**Comment by jeff-dagenais** [comment]
Exact same here. I have no time to debug now though.

**Comment by johnste** [comment]
Won't have time to look at this for now, hopefully next week.

Some questions though:
- Does it only happen when you save in VS Code?
- Are you using any VS Code extentions like custom formatters like prettier, or plugins that act on the file after or before it is saved?

**Comment by jeff-dagenais** [comment]
I did disable `"javascript.format.enable": false` as well as `"editor.formatOnSave": false`, it is still doing the problem.

I hate to say it, but it may be one of those times a short `sleep` would help?? 🤢 Yeah, perhaps some more investigating before throwing the towel though. 😉

**Comment by xiaobq** [comment]
I tried in system text editor and there is no error. Seems it's an issue for VS code only.
I use ESLint, but I don't use Prettier. 
I'm not sure if I use any plugins that act on the file after or before it is saved because I don't know how to check it.

**Comment by johnste** [comment]
Yes I can reproduce this issue too. Adding a 100 ms delay seems to fix the issue, so I pushed that change right now in [this commit](https://github.com/johnste/finicky/commit/b1e870b7a04645d887237667ab46ab1d8e52962d). Next release will contain this fix, hopefully sometime in November.

**Comment by johnste** [comment]
Fixed in v3.1.3 https://github.com/johnste/finicky/releases/tag/v3.1.3
