### ISSUE TITLE
Zoom links not opened in native zoom.us app instead in browser 

### ISSUE THREAD

**Issue by sceiler** [johnste/finicky#141]
I tried different configurations using example in the Wiki as well as using the kickstart but no configuration works in opening a Zoom link in the native Zoom app. Instead it always opens the default browser. Using the console I confirmed that it should open correctly but it does not.

I tried these but all of them open in the browser as I said. I am on the latest version 3.1.1 and on macOS 10.15.7
```
match: /^https?:\/\/.*zoom\.us\/j.*$/,
browser: "Zoom.us.app"

match: /^https?:\/\/.*zoom\.us\/j.*$/,
browser: "zoom.us.app"

match: /^https?:\/\/.*zoom\.us\/j.*$/,
browser: "/Applications/zoom.us"

match: /^https?:\/\/.*zoom\.us\/j.*$/,
browser: "/Applications/zoom.us.app"

match: /^https?:\/\/.*zoom\.us\/j.*$/,
browser: "zoom.us"

match: /^https?:\/\/.*zoom\.us\/j.*$/,
browser: "Zoom.us"
```

**Comment by xiaobq** [comment]
it's answered in [config idea](https://github.com/johnste/finicky/wiki/Configuration-ideas) page as below.

```
{
  match: /zoom.us\/j\//,
  browser: "us.zoom.xos"
}
```

**Comment by sceiler** [comment]
@xiaobq I tried this as well but it does not work like with the other configs I tried.

For clarification I open the Zoom links in Slack. There is a Zoom integration for Slack which allows you to create Zoom meeting ad-hoc. After clicking on a button it will open a Zoom link. Maybe this is something finicky can't pick up?

**Comment by johnste** [comment]
Does the integration look like this? 
![bild](https://user-images.githubusercontent.com/886051/98252893-b9e20280-1f7a-11eb-8084-006cf8fe79dd.png)

I used [this trick](https://github.com/johnste/finicky/wiki/Troubleshooting-&-Tips#i-want-to-see-all-incoming-parameters-to-the-url-handling-functions) to look at the url it's trying to open and it appears to use a different format now:

`https://applications.zoom.us/event/callback/slack/<NUMBER>?startUrl=BASE64&state=BASE64&sig=HEX`

Might be able to get it working by opening urls like this in the zoom client directly, but needs some attempts.

**Comment by sceiler** [comment]
Yes this is what it looks like. I think this is then redirected to the standard Zoom URL "companyname.zoom.us...". I will fiddle around with the format you are seeing. Thanks!

**Comment by dkoleary88** [comment]
Have you taken a look this ticket @sceiler? https://github.com/johnste/finicky/issues/89

**Comment by sceiler** [comment]
> Have you taken a look this ticket @sceiler? https://github.com/johnste/finicky/issues/89

Thanks I just glanced over the issue. That looks really promising and what I'm looking for. I need to check this out when I find time. It probably needs also some additional fiddling from me as I also sometimes click on Zoom links out of Google Calendar where the URL looks a tiny bit different (zoom is part of the url as a parameter).

**Comment by Luminus** [comment]
I modified @xiaobq's snippet above and got it to work just fine like this:

```js
{
    match: [
      "zoom.us*",
      finicky.matchDomains(/.*\zoom.us/),
      /zoom.us\/j\//,
    ],
    browser: "us.zoom.xos"
}
```

**Comment by johnste** [comment]
Great, looks like we have a working solution. I added this to the wiki https://github.com/johnste/finicky/wiki/Configuration-ideas#open-zoom-links-in-zoom-app

**Comment by jondkinney** [comment]
In my testing, I think it'd work better if we included the `/j` portion of the path in the regex matches. That way it only forces the zoom app to open up links that'll work for meetings. Examples:

* https://zoom.us/j/1234567890
* https://us06web.zoom.us/j/1234567890
* https://acme-company.zoom.us/j/1234567890
* https://us02web.zoom.us/j/1234567890?pwd=XWYZXEYOUGFNE9ZYTFQUT01

Where as with out that, the native zoom app will try to open zoom url shortened links, the zoom link to find your local phone number, and zoom recording links. 

* https://us02web.zoom.us/my/acme.user
* https://us06web.zoom.us/u/kb4QT2gToQ
* https://us02web.zoom.us/rec/share/zxeyougf-bigstring?startTime=1641584922000

```
    {
      // make zoom links open in zoom
      match: [
        "zoom.us/j/*",
        finicky.matchDomains(/.*\zoom.us\/j/),
        /zoom.us\/j\//,
      ],
      browser: "us.zoom.xos",
    },
```

**Comment by saurabhshri** [comment]
Thanks @jondkinney! Login and SSOs were failing for me because it kept redirecting to the app. Edited the wiki to use your config https://github.com/johnste/finicky/wiki/Configuration-ideas#open-zoom-links-in-zoom-app
