### ISSUE TITLE
Any better way to make the code shorter for removing martketing tags from URL?

### ISSUE THREAD

**Issue by xiaobq** [johnste/finicky#143]
I like the idea to remove all marketing/tracking information from urls.
[The configuration idea page](https://github.com/johnste/finicky/wiki/Configuration-ideas) shared an example with tag prefix "utm_".

But there are many other tags.
For example, I want to remove marketing tag "from_voters_page" too.
Here is my config. Basically I copy and paste the code for "utm_" and adapt it for the new tag.

```

    {
      match: ({ url }) => (url.search.includes("utm_")),
      url({ url }) {
        const search = url.search.split('&').filter(part => !part.startsWith("utm_"));
        return {
          ...url,
          search: search.join('&')
        }
      }
    },
    {
      match: ({ url }) => (url.search.includes("from_voters_page")),
      url({ url }) {
        const search = url.search.split('&').filter(part => !part.startsWith("from_voters_page"));
        return {
          ...url,
          search: search.join('&')
        }
      }
    }
```

**Questions:**

1. Is there a way to put all of the tags in a list, then I can check it against the list so that I can write this piece of code once for all tags in the list?
1. Another idea is we create a list for all tags, like the [shorten URLs page](https://github.com/johnste/finicky/blob/9ae03db0e4b25c535f6b524df409e4b28210037a/Finicky/Finicky/ShortUrlResolver.swift#L32), and then we check the tags against that list? Each item in the list can contain both domain and tag with format "domain:tags" so that we can restrict some tags for some domain only. if domain is not specified, the tags applies to all domains.

**Comment by johnste** [comment]
You could do something like this. There's an array of keys you want to remove (like `from_voters_page`), and another array with keys you want to remove if they match the start of a key (like the `utm_` prefix)

I made the match function always return true since it doesn't really matter if the code runs on every url finicky opens, but you could refactor it and extract a function using those keys to only match when necessary, or if it's important that it only matches on some domains.

```js 

module.exports = {
  defaultBrowser: "Safari",

  rewrite: [
    {
      match: ({ url }) => true,
      url({ url }) {
        const removeKeysStartingWith = ["utm_"];
        const removeKeys = ["from_voters_page"];

        const search = url.search
          .split("&")
          .map((parameter) => parameter.split("="))
          .filter(([key]) =>
            removeKeysStartingWith.some(
              (startingWith) => !key.startsWith(startingWith)
            )
          )
          .filter(([key]) => removeKeys.some((removeKey) => key !== removeKey));

        return {
          ...url,
          search: search.map((parameter) => parameter.join("=")).join("&"),
        };
      },
    },
  ],
};

```

I don't think filtering query parameters is intrinsic enough for Finicky to do so would prefer to keep examples like this in the wiki instead rather than add specific functionality for it.

**Comment by xiaobq** [comment]
Thanks a lot John.  You got my idea. 
It works well with key prefix "utm_" and key "from_voters_page". 
But if I add more key prefixes and keys, it can't recognize them. 
I don't use JS so maybe I haven't coded it properly.  Hope you can help me on that.

For example, here is the URL I tried to test.

> https://example.com?utm_srer=34w&utm_aa=3ew&from_voters_page=ee&abc=333&uta_srer=1

you can see it has 2 key prefixes: utm_, uta_
and 2 keys: from_voters_page, abc

Here is my code.

```
  rewrite: [
    {
      match: () => true,
      url({ url }) {
        const removeKeysStartingWith = ["utm_", "uta_"];
        const removeKeys = ["from_voters_page", "abc"];

        const search = url.search
          .split("&")
          .map((parameter) => parameter.split("="))
          .filter(([key]) =>
            removeKeysStartingWith.some(
              (startingWith) => !key.startsWith(startingWith)
            )
          )
          .filter(([key]) => removeKeys.some((removeKey) => key !== removeKey));

        return {
          ...url,
          search: search.map((parameter) => parameter.join("=")).join("&"),
        };
      },
    }
  ],
```

However, it exports like below.

>https://example.com?utm_srer=34w&utm_aa=3ew&from_voters_page=ee&abc=333&uta_srer=1

![image](https://user-images.githubusercontent.com/12482876/98459989-fca21580-21da-11eb-8824-03d3c2e30475.png)

**Comment by johnste** [comment]
Oh, apologies, I made a mistake writing the conditions. I hope this one works better:

```js
module.exports = {
  defaultBrowser: "Safari",

  rewrite: [
    {
      match: ({ url }) => true,
      url({ url }) {
        const removeKeysStartingWith = ["utm_", "uta_"];
        const removeKeys = ["from_voters_page", "abc"];

        const search = url.search
          .split("&")
          .map((parameter) => parameter.split("="))
          .filter(
            ([key]) =>
              !removeKeysStartingWith.some((startingWith) =>
                key.startsWith(startingWith)
              )
          )
          .filter(
            ([key]) => !removeKeys.some((removeKey) => key === removeKey)
          );

        return {
          ...url,
          search: search.map((parameter) => parameter.join("=")).join("&"),
        };
      },
    },
  ],
};
```

**Comment by xiaobq** [comment]
It works very well. Really appreciate it. Thanks a lot John.
You may update this new version into your configuration idea page. :)
