### ISSUE TITLE
Add a config step to set Finicky run at startup

### ISSUE THREAD

**Issue by xiaobq** [johnste/finicky#144]
Hi @johnste

I find my Finicky was not running when I restarted my Mac (I haven't restarted it for a long time). Then I realized I haven't added it to the startup list. 

I understand Finicky doesn't have a config option to set run on startup. If that's the case, can you add a config step in the config documentation page to share the user can add Finicky to Mac startup list?

Correct me if Finicky already has a config to run on startup.

**Comment by johnste** [comment]
Hi!

Generally there shouldn't be a need to run Finicky at startup, since the idea is to use is as the default browser, which will automatically be launched whenever someone clicks a link. So it's okay if it's not running before that, and it is quick to launch too.

**Comment by xiaobq** [comment]
Make sense. No need to run it at startup. Thanks John.
