### ISSUE TITLE
Possible to run Finicky with 2 different configurations?

### ISSUE THREAD

**Issue by huyz** [johnste/finicky#154]
I'm trying to make Finicky and Browserosaurus work together in a custom way for me. In short, I need logic that goes like this: 1. Automation, 2. Prompt me, and 3. Automation

1. I'd like one Finicky working with a first-stage config, which decides whether it can automate opening the right browser with the right profile.
2. If Finicky can't match, then Browserosaurus is invoked and most of the time I would select Finicky (except sometimes I would select a different browser for development purposes)
3. When the second Finicky is selected, I'd like it to read a different config that opens a specific browser with a specific profile.

Is that doable?

**Comment by johnste** [comment]
This could be possible by adding some sort of unique tag to the url being opened, e.g. trying to open http://example.com but adding http://example.com#finicky to it before sending it to Browserosaurus, and then detecting the anchor in the finicky rules to treat it differently.

Not sure if that would work for you, it's a bit awkward though. Finicky can't read different configurations at this point, but that's also an interesting idea.

**Comment by johnste** [comment]
Actually, come to think of it, you could also create configuration rules that only act if the url was opened by Browserosaurus itself, a lot less awkward. You can use the `sourceBundleIdentifier` or `sourceProcessPath` to do this. I'm closing this issue, but if you're still looking for a solution for this and need help please let me know and/or reopen this.
