### ISSUE TITLE
Enable profile support for Vivaldi

### ISSUE THREAD

**Issue by n3f** [johnste/finicky#155]
As this is a chromium browser, I hoped the profile support would work on it as well.  Sadly, I haven't had much success with it, so I assume it's a code fix.

**Comment by johnste** [comment]
Yeah makes sense, we should definitely do this.

**Comment by johnste** [comment]
Released in [3.2.0](https://github.com/johnste/finicky/releases/tag/v3.2.0)

**Comment by n3f** [comment]
Thanks, working a treat! 👍
