### ISSUE TITLE
auto redirect to result of "I feel lucky" by Google

### ISSUE THREAD

**Issue by ashkrosh** [johnste/finicky#157]
Hi
There are numerous Chrome extensions and greasemonkey scripts to auto-redirect to the result of "I feel lucky" and I wonder if we could have something like this in finicky?

Context: https://stackoverflow.com/questions/53801313/javascript-get-redirected-link-from-googles-im-feeling-lucky-function

Best

**Comment by johnste** [comment]
Interested to hear about the use case for this. When would this be useful?

I guess this could be implemented but it's not anything I'm going to prioritize myself.

**Comment by johnste** [comment]
Closing unless there are any updates
