### ISSUE TITLE
Match by Slack workspace

### ISSUE THREAD

**Issue by gabrielfeo** [johnste/finicky#158]
Would it possible to know which Slack workspace the URL was opened from in the Slack app? I realize it's not a current feature, but would be nice for people with multiple workspaces. Company A and Company B each have their own Slack workspace and GSuite account. I'd like to have links from A's workspace open in A's Chrome profile, and so on.

**Comment by johnste** [comment]
Closing this - let's keep this discussion in #96

**Comment by zerodayyy** [comment]
@johnste #96 is for a different issue. I think this is specifically about matching the Slack workspace when opening arbitrary links in Slack, not deep-linking

**Comment by ShahOdin-ovo** [comment]
@johnste 
not sure if #96 can help. 😞 

@gabrielfeo guessing you haven't had any luck with this?

**Comment by gabrielfeo** [comment]
> @johnste 
> 
> not sure if #96 can help. 😞 
> 
> 
> 
> @gabrielfeo guessing you haven't had any luck with this?
> 
> 

Nope. #96 is indeed a different issue. 

Also, I don't have any ideas on how to implement what I suggested.

**Comment by totsamyroma** [comment]
Hey @gabrielfeo 👋 

Checkout my PR ☝️ 
It [adds](https://github.com/johnste/finicky/pull/507) missing functionality from your request
