### ISSUE TITLE
Specify the Google profile

### ISSUE THREAD

**Issue by samo9789** [johnste/finicky#162]
Hi, 

Thanks for making this application, I would like to suggest that people that are picky about which browser to run for given sites might go as far as setting up different profiles for different domains (I know I do)
I think it would be great to be able to write 

browser: 'Google Chrome --profile-directory="Profile 15"'

or maybe

browser: 'Google Chrome',
params: '--profile-directory="Profile 15"'

in the configuration and have these params used when launching chrome

By the way, if you want to know what profile to use, open that profile in chrome and go to chrome://version, you will see the current profilePath

Of course, these params could be used for other features like starting incognito, starting in mode that allows for unsecure sites, etc et

Thanks a lot

**Comment by johnste** [comment]
You can specify the Chrome profile to use, see https://github.com/johnste/finicky/wiki/Configuration#2-you-can-define-more-options-with-a-browser-object

Example:
```js
{
  match: "example.com/*",
  browser: { 
    name: "Google Chrome",
    profile: "Default", 
  }
},
```

**Comment by johnste** [comment]
Closing since this seems to be solved, let me know if I misunderstood anything.

**Comment by sfdye** [comment]
Hi is it possible to specify a default profile at the global browser level? For example I want to open all links in Home profile by default and others (matching rules) in Work profile
