### ISSUE TITLE
How can I rewrite a URL and use it in Terminal?

### ISSUE THREAD

**Issue by dillonjohnbrown** [johnste/finicky#170]
I want to use Finicky to rewrite URLs then use the rewritten URL in a Terminal command.

The URLs start out like this:
`https://www.youtube.com/watch?v=HsStKuWHI_c`

and I would like them to end up like this:
`https://youtu.be/HsStKuWHI_c`

Next, I want to open Terminal and have it do the command:
`youtube-dl https://youtu.be/HsStKuWHI_c`

How can I configure my `.finicky.js` file to rewrite URLs in this format then use them in Terminal?

**Comment by dillonjohnbrown** [comment]
I've managed to get the rewrite almost there. With the following code, `https://www.youtube.com/watch?v=HsStKuWHI_c` returns `https://youtu.be/v=HsStKuWHI_c`. I just need help removing the `v=` from the url.
```
rewrite: [
    {
        match: ({ url }) => url.host.endsWith("youtube.com"),
      		url: ({ url }) => {
      			return {
      				"host": "youtu.be",
      				"pathname": "/" + url.search,
      				"search": ""
      			}
      		}
      	}
]
```

**Comment by dillonjohnbrown** [comment]
I figured out how to get the URL from Finicky into a shell script, but now my `youtube-dl` isn't working as expected.

.finicky.js
```
handlers: [
    {
        match: /^https:\/\/youtu\.be\/.*$/,
        browser: "com.apple.ScriptEditor.id.open-URL"
    }
]
```

AppleScript
```
#!/bin/zsh
on open location input
    do shell script "/usr/local/bin/youtube-dl  " & input
end open location
```

Running `youtube-dl https://youtu.be/HsStKuWHI_c` in Terminal works just how I want it to, but using this AppleScript leaves me with a separate video file and audio file. Maybe this is something unrelated to Finicky and I should seek help on Stack Exchange.

**Comment by johnste** [comment]
Your Finicky config looks ok to me, so maybe there's another issue here. Does running the applescript directly work? I'm not sure I can help.

**Comment by dillonjohnbrown** [comment]
Thanks for checking this thread out!

Hardcoding the URL into the AppleScript yields the same result -- two unmerged files. Normally, when I use youtube-dl from Terminal, it does some magic with ffmpeg and the two files are combined into one. By using this AppleScript it is like it doesn't do the ffmpeg part. Thanks for taking a look at this thread, and of course for Finicky!

I just asked on Stack Exchange for help https://apple.stackexchange.com/questions/413004/typing-into-terminal-works-applescript-partially-works
