### ISSUE TITLE
Links from apps(Slack, Zoom) focusing browser even when openInBackground = true

### ISSUE THREAD

**Issue by noel-jean-paul** [johnste/finicky#174]
I want to open links from Slack and not have focus redirected to the browser when I do.
As such, I can open multiple links in Slack, then switch to a browser to check them all out.

I assumed that the openInBackground option is intended for this behaviour.
Attempted to fix using issue #107 but no luck with either Chrome or Safari. They both come to the foreground when a link is clicked.

My config 
```
module.exports = {
  defaultBrowser: "com.google.Chrome",
  options: {
	logRequests: true
  },
  handlers: [
    {
      // Valid keys are: shift, option, command, control, capsLock, and function.
      match:() => finicky.getKeys().command,
      browser: {
	name: "com.google.Chrome",
	openInBackground: true
      }
    }
  ]
};

**Comment by johnste** [comment]
Thanks, I'll investigate.

**Comment by johnste** [comment]
Chrome can't be opened in the background because of a bug in Chrome, please see https://github.com/johnste/finicky/issues/71 

Can't do anything about it really, sorry. :(

**Comment by noel-jean-paul** [comment]
No worries, thanks for looking into it :)
I'll hold out hope that the Chrome bug gets fixed eventually.
