### ISSUE TITLE
Generic protocol handler

### ISSUE THREAD

**Issue by luckman212** [johnste/finicky#175]
I stumbled in here hoping there was a way to use Finicky to intelligently route `mailto:` links based on the recipient. E.g. I always want mail destined for `joe@acme.com` to be routed to Gmail, but everything to use Fastmail. The URL rewriting feature of Finicky would be useful here, since these services require different parameters in their URI strings.

I saw #104 from a year ago, but it seems like there's not much interest in that use case. Anyone know of a better way to handle this? I'm thinking of trying to make a custom URL handler in Hammerspoon.

**Comment by johnste** [comment]
I think using Hammerspoon makes sense for now. It's hard to support a lot of features given my limited time. I hope it works out for you!

**Comment by luckman212** [comment]
No worries! Thanks for the response, I'll try the Hammerspoon route and post back here if I have any luck for everyone's benefit.

**Comment by floriandierickx** [comment]
Hey @luckman212 , I stumbled on this idea after having submitted a feature request for handling `file://`-links recently (and preferably parse/change the url structure using regex, ..) #200 

Did you find a way to do this with Hammerspoon? I would like to have a look at how it could be implemented in finicky, but I'm quite new in XCode-projects. If it is deemed possible, I would like to have a look at it some day.

**Comment by luckman212** [comment]
@floriandierickx I looked into it, and it seems easy enough to do in Hammerspoon. But right around that time I stumbled onto [OpenIn](https://loshadki.app/openin/) which fills this need perfectly. Highly recommend checking it out.

**Comment by floriandierickx** [comment]
Hey @luckman212, thanks for the suggestion, I didn't know that application yet. So much interesting OSx-applications in all corners of the internet ! :) For others who read along: I installed the trial, but at the moment - if I'm not mistaken - I did not find an option/tweak to make OpenIn handle `file://`-links (only `mailto:`). Maybe I overlooked something..
