### ISSUE TITLE
Ability to pass parameters to browsers when opening links

### ISSUE THREAD

**Issue by alejandroivan** [johnste/finicky#178]
**Is your feature request related to a problem? Please describe.**
Everytime Google Chrome is closed (not running in background) and with the "continue where you left of" option turned on (and tabs opened from the last session of course), and you click on a link, it will open a window with all the last tabs opened, with another window where the actual link opens.

**Describe the solution you'd like**
A clear solution is to pass the `--parent-window` argument to Google Chrome, which will force it to open the link in the already opened window. This could extend to any other app really (like passing the incognito parameters or so).

**Describe alternatives you've considered**
I considered using `browser: "Google Chrome --parent-window` but it didn't work, since Finicky can't find the actual app package with that.

A good way to pass the parameter would be to allow to pass that parameter (or any parameter really) to the Chrome app bundle. I guess if adding an optional `parameters` option to the Javascript, to the side of `browser` would be enough. Maybe a string like:
```
    browser: "Google Chrome",
    parameters: "--parent-window --any-other-param"
```

Or, even better, an array:
```
    browser: "Google Chrome",
    parameters: [ "--parent-window", "--any-other-param" ]
```
The `open` command already considers this, replacing `open -a "Google Chrome" URL` with `open -a "Google Chrome" --args --parent-window URL`.

**Additional context**
To reproduce: Go to Chrome preferences and enable "continue where you left of" in "on startup". Then open two tabs and quit the browser by letting Cmd+Q pressed. With the browser closed, open any link using Finicky that would make it open Chrome. Two windows appear, with your last session on one and the link opened in the other window.

**Comment by johnste** [comment]
I haven't had a chance to document this feature yet, but it's already available. Please see[ this PR](https://github.com/johnste/finicky/pull/160) for an example, and please let me know if it works for you or not.

**Comment by alejandroivan** [comment]
@johnste I tried it using Finicky 3.3.1 and it says it's not available (`Error: unknown key args at module.exports...`).
Also, it looks like it works for specific handlers, but not for the `defaultBrowser`. I might be wrong on this.

**Comment by alejandroivan** [comment]
Okay, this one worked for me. I'm leaving my `.finicky.js` file for reference.

```
// ~/.finicky.js

module.exports = {
    defaultBrowser: (options) => ({
        "name": "Google Chrome",
        "args": [ "--parent-window", options.urlString ]
    }),
    rewrite: [],
    handlers: [
      {
        // Open Facebook in Safari
        match: /^https?:\/\/(www.)?facebook.com(\/.)*/,
        browser: "Safari"
      },
      {
        // Open LinkedIn in Safari
        match: /^https?:\/\/(www.)?linkedin.com(\/.)*/,
        browser: "Safari"
      },
      {
        match: "https://www.figma.com/file/*",
        browser: "Figma",
      },
      {
        match: finicky.matchHostnames(['teams.microsoft.com']),
        browser: 'com.microsoft.teams',
        url({ url }) {
          return {
            ...url,
            protocol: 'msteams',
          };
        },
      },
      {
        match: "open.spotify.com/*",
        browser: "Spotify"
      }
    ]
  };
```
