### ISSUE TITLE
your binary release of Finicky 3.3.1 crashes opening "activity-watcher" dashboard, self-build doesn't

### ISSUE THREAD

**Issue by slippycheeze** [johnste/finicky#179]
**Describe the bug**
Your binary release of Finicky 3.3.1 crashes when I open the [activity-watcher]() dashboard from the menubar applet.
Versions that I built myself, from HEAD, and from the v3.3.1 tag, in both Debug and Release configurations, both work fine.

The console output of your binary release is:
```
] ./Finicky.app/Contents/MacOS/Finicky
Start listening to file changes
Reloading config
Valid config ✅
Checking for updates:
    Current version: v3.3.1
    Available version: v3.3.1
    Latest version seen: v3.3.1
[1]    17311 illegal hardware instruction  ./Finicky.app/Contents/MacOS/Finicky
```

A crash-dump file is attached: [Finicky_2021-03-08-122342_C02CH1EBLVDN.crash.txt](https://github.com/johnste/finicky/files/6101032/Finicky_2021-03-08-122342_C02CH1EBLVDN.crash.txt)

Unfortunately, as noted, I can't reproduce this with debug symbols, and I can't attach a debugger to the binary build.

**Your configuration**
```javascript
module.exports = {
  defaultBrowser: (data) => {
    finicky.log(JSON.stringify(data, null, 2));
    return { name: 'com.browserosaurus', appType: 'bundleId' };
  },
};
```

The console output generated from running this in the working (that is, self-built, unsigned) version: 
[finicky-console-data.txt](https://github.com/johnste/finicky/files/6101074/finicky-console-data.txt)

**platform details**
```
] sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524
] uname -a
Darwin C02CH1EBLVDN 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
```

**To Reproduce**
1. Download the binary release from github: `curl -LO "https://github.com/johnste/finicky/releases/download/v3.3.1/Finicky.zip"`
2. Run it, using my config above, or even just a static string default browser and nothing else.
3. Crash!

Again, as noted, if I build it myself locally then I don't get the crash.  -_-

**Comment by johnste** [comment]
Thanks for reporting. I'll push out a new release soon. I'm assuming it has something to do with this issue https://github.com/johnste/finicky/issues/171

**Comment by johnste** [comment]
Just published a new release, hopefully it works better for you.

**Comment by slippycheeze** [comment]
I can confirm that this fixed the problem for me.  Thank you for your quick response.

As a side note #171 mentions "running from source", which I'm not sure how to do—but may have shed more light on this?
