### ISSUE TITLE
Matching multiple conditions

### ISSUE THREAD

**Issue by scottslowe** [johnste/finicky#204]
I'd like to configure Finicky to open `docs.google.com` (and related URLs) in Firefox, but _only when opened from the Slack app._ I know how to match against the destination, and I have seen examples on matching against the opener, but I don't know how to match against both (if that's even possible).

I tried this configuration:

```
      {
        // Open Google Docs in Firefox if opened from Slack
        match: ({ opener }) => opener.bundleId === "com.tinyspeck.slackmacgap" && ({ url }) => url.host.includes("docs.google.com"),
        browser: "Firefox"
      }
```

However, Finicky reports a configuration error. What am I missing? (I apologize if this is an obvious error, I'm not a JavaScript expert.)

**Comment by johnste** [comment]
You almost had it, this should work:

```js
 {
    // Open Google Docs in Firefox if opened from Slack
    match: ({ opener, url }) => opener.bundleId === "com.tinyspeck.slackmacgap" && url.host.includes("docs.google.com"),
    browser: "Firefox"
  }
```

**Comment by scottslowe** [comment]
That works, thanks! Is it worth updating the wiki with this? (I'm happy to do so, if you'd like.)

**Comment by johnste** [comment]
Sure, please go ahead!

**Comment by scottslowe** [comment]
I've updated the wiki. I'll go ahead and close this issue since it is now resolved. Thank you!
