### ISSUE TITLE
Feature request: Open URL in whatever browser is currently open

### ISSUE THREAD

**Issue by joshtch** [johnste/finicky#21]
As I [mentioned](https://www.reddit.com/r/macapps/comments/3fuxku/finicky_a_scriptable_browser_launcher_os_x_1010/ctxnh11) on Reddit, I'd like to use Finicky to open the URL in whatever browser happens to be open, with a hierarchy of preference for tiebreaks. This could be done with a system call to `ps`, or via an AppleScript command like [the one I found here](http://hints.macworld.com/article.php?story=20100503134708927).

**Comment by johnste** [comment]
Hm, I think I would rather expand the javascript API to allow for this, rather than bringing in another scripting language.

**Comment by joshtch** [comment]
Okay, sure. What do you have in mind? I figured plugging into an existing language would make Finicky a lot more powerful without adding much complexity. Frankly, I find it a little curious to be using a Javascript API in the first place...

**Comment by johnste** [comment]
Finicky started out heavily inspired by [Phoenix](https://github.com/kasper/phoenix/), which also is scriptable with javascript. I like the Javascript approach since it's easier to make a small and clean API. And furthermore, I have never used AppleScript (but I should give it a shot some day). 

I'll try to spend some time later tonight to try and figure out a suggestions for handling this.

**Comment by johnste** [comment]
Maybe simply returning an array of bundle identifiers from a handler could work. 

```javascript
finicky.onUrl(function(url, opts) {
    return {
        bundleIdentifier: ['com.google.Chrome', 'com.apple.Safari', 'com.operasoftware.Opera']
    }
});
```
However, if there is a need to open multiple browsers in the future, this might be an issue.

**Comment by joshtch** [comment]
Interesting thought, and one that would work for my use-case, I think. Seems like a lot of web developers would want to be able to open a link in multiple apps, though.

**Comment by johnste** [comment]
Could probably be solved with some sort of flag or different option, though. But the API needs to stay clean and obvious..

**Comment by joshtch** [comment]
I agree with you there, on keeping the API clean.

**Comment by johnste** [comment]
Working on this. I'll go for the array solution for now - opening multiple browsers for one link is probably not a really common use case and if ever implemented, could be done in a more explicit way than this.
