### ISSUE TITLE
base64 functions aren't available (`atob`, `btoa`, `Buffer`)

### ISSUE THREAD

**Issue by bigethan** [johnste/finicky#223]
**Describe the bug**
I'm trying to base64 decode a url to extract some information to point to the right browser, and these functions give a ` Configuration: ReferenceError: Can't find variable`. Is there a way to get at these that doesn't involve putting a polyfill into my config? It's quite possible I've missed something, but haven't found things after looking for a while.  Any guidance would be appreciated!

**Your configuration**
seems to be irrelevant of the config

**To Reproduce**
use `atob` or `Buffer.from` on a string in a matcher

**Comment by johnste** [comment]
Unfortunately `atob` are not available in JavaScriptCore as far as I know, we would need to load a polyfill either in the config or add it to finicky's own js client layer.

**Comment by bigethan** [comment]
thanks for the info, will start with my config unless it's a thing that you do want in the client layer in which case I could PR something.
