### ISSUE TITLE
Profile selector for Brave not working anymore

### ISSUE THREAD

**Issue by FezVrasta** [johnste/finicky#232]
**Describe the bug**
I used to be able to open some links with a particular Brave profile, but lately it stopped working and it just opens it with the default profile instead.

**Your configuration**
```
// Use https://finicky-kickstart.now.sh to generate basic configuration
// Learn more about configuration options: https://github.com/johnste/finicky/wiki/Configuration

const BRAVE_PERSONAL = { name: 'Brave Browser', profile: 'Default' };
const BRAVE_WORK = {
  name: 'Brave Browser',
  profile: 'Work',
};

module.exports = {
  options: {
    hideIcon: false,
  },
  defaultBrowser: BRAVE_PERSONAL,
  handlers: [
    // Work
    {
      match: /^https?:\/\/.*work.*$/,
      browser: BRAVE_WORK,
    },
    // Slack
    {
      match: ({ url, opener }) => opener.path === '/Applications/Slack.app',
      browser: BRAVE_WORK,
    },
    // Zoom
    {
      match: ({ url, opener }) =>
        url.host === 'zoom.us' && opener.path !== '/Applications/zoom.us.app',
      browser: '/Applications/zoom.us.app',
    },
    {
      match: ({ url }) => url.host === 'localhost',
      browser: BRAVE_WORK,
    },
  ],
};
```

**To Reproduce**

Click on a link that matches my handlers for the WORK profile.

I noticed that if I change `profile: 'Work'` to anything else it seems to completely ignore it, previously it used to launch a new profile.

**Comment by AndreaBarghigiani** [comment]
@FezVrasta can I ask why you close this one? I am on the latest version of Finicky but each time I ask it to open a link in a specific profile it opens a new window with *Person 1* as profile, profile that I've never created.

Did you solve your issue and now are able to open links in a specific profile?

**Comment by AndreaBarghigiani** [comment]
Nevermind, discovered that even if I had folders with the same name of my profile the ones that Finicky will open are `Default` and `Profile 1`.

To be sure that you'll select the right folder name go to `chrome://version` and check the *Profile Path*.

**Comment by AndreaBarghigiani** [comment]
Thanks for coming by anyway, mine is a different solution but the important thing is that it works for the both of us 😊
