### ISSUE TITLE
Outlook Safelinks

### ISSUE THREAD

**Issue by sepsamavi** [johnste/finicky#241]
**Is your feature request related to a problem? Please describe.**
Some professional Exchange email servers force users to have Microsoft's so-called [Safelinks](https://support.microsoft.com/en-us/office/advanced-outlook-com-security-for-microsoft-365-subscribers-882d2243-eab9-4545-a58a-b36fee4a46e2). The Safelinks feature forces all links in an email to be replaced with something of the form `https://xxx.safelinks.protection.outlook.com/xxxxxxx` Thus, when opening any links from that Exchange account in the Mail app, Finicky does not route as expected since the original link is not visible to Finicky. 

**Describe the solution you'd like**
Would it be possible to configure Finicky such that for all links of the form `https://xxx.safelinks.protection.outlook.com/xxxxxxx`, Finicky first evaluates the redirect from outlook to the underlying link, and then pushes the underlying link (that outlook redirected to) to the appropriate browser based on the Finicky config file?

**Comment by johnste** [comment]
There is already a short url resolver in Finicky that attempts to resolve short urls such as https://tinyurl.com/5yhwcvh7. It uses a whitelist of domains it tries to resolve urls for. You can add more domains in that list, please see the `urlShorteners` open mentioned here https://github.com/johnste/finicky/wiki/Configuration#general-options

![image](https://user-images.githubusercontent.com/886051/162609811-e6052c7f-c73f-43e5-a5d7-5f74f210ab9e.png)
Example: Opening `https://tinyurl.com/5yhwcvh7` in Finicky automatically resolves it to the final url on youtube.

**Comment by sepsamavi** [comment]
Wonderful, Thanks! I had overlooked the ability to extend the list  `urlShorteners`.

**Comment by thoroc** [comment]
The documentation link is broken, but I am guessing that a regex matcher would do the trick in v4.

[edit]
I cannot get it to work; I want to open those to Firefox, but instead it goes to the _default_ browser. What is happening is that I have a link a company gitlab space that is provided in MS Teams. Upon clicking on this link I get a redirect through the following url to the destination gitlab url (repo).

- **Link** `https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html`
- **config**
```typescript
import type { FinickyConfig } from '/Applications/Finicky.app/Contents/Resources/finicky.d.ts';

export default {
  defaultBrowser: 'com.apple.Safari',
  options: {
    // Check for updates. Default: true
    checkForUpdates: true,
    // Log every request to file. Default: false
    logRequests: true,
  },
  handlers: [{
    match: [
      // doesn't work
      (url: URL, { opener }) => {
        return (
          url.host === 'statics.teams.cdn.office.net' &&
          url.pathname.startsWith('/evergreen-assets/safelinks/1/atp-safelinks.html')
        );
      },
      // doesn't work either
      'https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html',
    ],
    browser: 'org.mozilla.firefox',
  }],
} satisfies FinickyConfig;
```

**Comment by thoroc** [comment]
I see there is a discussion that might be addressing this: https://github.com/johnste/finicky/discussions/369
