### ISSUE TITLE
Google Chrome Profiles

### ISSUE THREAD

**Issue by petty** [johnste/finicky#248]
When using Chrome as the destination browser, it would be amazing if I could specify a profile too.

For example, I might want to open a particular domain with "Google Chrome Default profile" vs "Google Chrome Work profile" or maybe for Finicky, something like the command line arguments:

`open -a "Google Chrome" --args --profile-directory=Default`

**Comment by jeannnemelanie** [comment]
+1

**Comment by petty** [comment]
That is awesome.

**Comment by jeannnemelanie** [comment]
Awesome! Thanks!
