### ISSUE TITLE
I was able to change the name of the wiki page but I'm not contributer

### ISSUE THREAD

**Issue by wildeyes** [johnste/finicky#260]
Are the permissions on the wiki correct? I was able to change the name of the configuration document instead of (what I thought would happen) making a suggestion to it's title.

**Comment by johnste** [comment]
Haven't restricted access to the wiki before – I did so now, but I'm not sure if people can still add to it then?

**Comment by wildeyes** [comment]
no, can't edit it now - so maybe open it but monitor for changes. BTW probably should return the name to configuration as it broke the link on the main page.

**Comment by johnste** [comment]
Opened the wiki for editing again. I can only restrict it to collaborators or nothing at all so I will keep it open for now I guess.

**Comment by wildeyes** [comment]
Yeah. Wondering tho if it emails you for edits so that at least your wiki can’t be “bombed” without you knowing?
