### ISSUE TITLE
Importing external JS files in finicky config file

### ISSUE THREAD

**Issue by nicoelayda** [johnste/finicky#261]
Is it possible to import external files into the main finicky config file?

I've tried ES6 imports
```javascript
import { CommonStuff } from "./common.js";

// Configuration: SyntaxError: Unexpected token '{'. import call expects exactly one argument.
```

```javascript
import CommonStuff from "./common.js";

// Configuration: SyntaxError: Unexpected identifier 'CommonStuff'. import call expects exactly one argument.

```

and Node.js `require`
```javascript
const CommonStuff = require("./common");

//Configuration: ReferenceError: Can't find variable: require
```

but none of them work. Is there any way to do this?

**My use case:**
I have two finicky `config.js` files (one for personal, one for work) but they share a lot of duplicated code. I want to move the common config into a `common.js`  file and import it into each config instead.

**Comment by johnste** [comment]
Sadly not supported at this point, no.

**Comment by nicoelayda** [comment]
**Update:** I've worked around this by transpiling my multiple config files with [webpack](https://webpack.js.org) and loading the generated `config.js` file into Finicky.

I've uploaded the webpack config I'm using [here](https://github.com/nicoelayda/finicky-config-webpack).
