### ISSUE TITLE
[Feature request] Ability to determine whether link was meant to be opened in background

### ISSUE THREAD

**Issue by EdenSG** [johnste/finicky#27]
Some software gives you the option to open a url in the background, but Finicky currently doesn't provide any way to use this information. Would this be feasible (as another boolean within `options.flags`)?

**Comment by johnste** [comment]
This is a feature as of Finicky 0.4. Finicky opens the browsers in the background if the source application tells it to. 

Check out the [API Documentation](https://github.com/johnste/finicky/wiki/Javascript-API-Documentation) if you want to force a link to open in the background or foreground.

Do you think there is a bug? If so, please let me know what software you're using. Thanks! :)

**Comment by EdenSG** [comment]
Ok, I'm having issues with Reeder, but I'll open a new issue.
