### ISSUE TITLE
iTerm2 integration with Finicky

### ISSUE THREAD

**Issue by clustor** [johnste/finicky#272]
**Have you tried creating configuration for this application?**

I added this handler but bundleId, name and path are all returning null.  I would like "open" command to launch URLs in a specific browser. 

`      match: ({ opener }) => {finicky.log("Received opener path " + opener.path
      + " opener name " + opener.name + " opener bundleId" + opener.bundleId); return false},
      browser: "Google Chrome"
    },
`

**Has anyone else tried to make this application work with Finicky before?**
I didn't see any references to integrating iTerm2. 

**What application are you trying to set up**
iTerm2 
`
/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' /Applications/iTerm.app/Contents/Info.plist                                                                                                   
com.googlecode.iterm2
`

**Comment by guyindc** [comment]
Thank you John for taking the time to answer!!! I gotta admit, I have no idea what on earth all that meant!!!  How do people understand programming so well. I come from a GUI type configuration interface, right when they were facing out command line. But it seems like command line can do so much more. I will have to sit down and do some reading. Appreciate the help. And if my some miraculous chance I succeed, I’ll let you know!!

Best
Kenny

On Jun 6, 2022, at 12:17 PM, clustor ***@***.******@***.***>> wrote:



Have you tried creating configuration for this application?

I added this handler but bundleId, name and path are all returning null. I would like "open" command to launch URLs in a specific browser.

match: ({ opener }) => {finicky.log("Received opener path " + opener.path + " opener name " + opener.name + " opener bundleId" + opener.bundleId); return false}, browser: "Google Chrome" },

Has anyone else tried to make this application work with Finicky before?
I didn't see any references to integrating iTerm2.

What application are you trying to set up
iTerm2
/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' /Applications/iTerm.app/Contents/Info.plist com.googlecode.iterm2

**Comment by kyounger** [comment]
It very much depends on _how_ the url is opened. 

If you're using the native link recognition functionality of iTerm (where you can Cmd+click on a link and it opens, the opener config should work (and works for me).

If some command in the shell is what is opening the url (e.g. `open http://127.0.0.1`, then you are effectively opening the url via a subprocess, and all properties on `opener` seem to be null, except `opener.pid`, which represents that `open` process — which subsequently quickly disappears as it's async.

**Comment by kyounger** [comment]
Just noticed this is a duplicate issue of #168 @johnste

**Comment by johnste** [comment]
Closing this in favor of #168
