### ISSUE TITLE
URLs that should open in background from Reeder app open in foreground

### ISSUE THREAD

**Issue by EdenSG** [johnste/finicky#28]
[Reeder 3 (beta)](http://reederapp.com/beta3/) gives the option to open links in the background, however Finicky doesn't appear to respect this and opens links in the foreground instead.

**Comment by johnste** [comment]
Reeder doesn't want to open links in Finicky at all without forcing, but I reproduced the issue with [Vienna RSS](http://www.vienna-rss.org/), so I'll see what's going on there.

**Comment by johnste** [comment]
Ok, unfortunately this seems to be a Chrome bug. Chrome and Chrome Canary doesn't seem to respect the NSWorkspaceLaunchOptions.WithoutActivation flag when opening urls. If I select Chrome as the default browser I can't open any links in the background. I tested with Safari and Firefox and they both work as expected.

Not sure I can do anything about this - I'll try to see if I can find any reported bugs for Chromium.

**Comment by johnste** [comment]
Of course, I am assuming you are using Chrome as your default browser.

**Comment by EdenSG** [comment]
Yes, I do. Thanks anyways!

**Comment by EdenSG** [comment]
It seems to be working normally for me (Chrome 47.0.2516), but I don't see any activity on the Chromium issue page. Strange.
