### ISSUE TITLE
Every link reprompts me to select Finicky as the default browser

### ISSUE THREAD

**Issue by seagullmouse** [johnste/finicky#288]
**Describe the bug**
- When I click on a link
- it opens using Finicky in the correct browser/profile
- The MacOS dialog opens asking if I want to keep Finicky or choose Chrome as the default browser
<img width="246" alt="image" src="https://user-images.githubusercontent.com/1561613/201367333-0c5e09c4-1e96-4da4-8495-c1e1cf644570.png">
<img width="611" alt="image" src="https://user-images.githubusercontent.com/1561613/201367383-ea4380cc-d779-4482-b381-dcb36a7c5a03.png">

**Your configuration**
```
...
defaultBrowser: {
        name: "Google Chrome",
        profile: "Default"
    },
...
```

I have tried to get Chrome to stop prompting but it will not do it!

**Comment by seagullmouse** [comment]
Is nobody else seeing this? It is super annoying

**Comment by gotrevor** [comment]
Yes, I'm seeing this too.  Unable to use Finicky without a fix for this.

**Comment by seagullmouse** [comment]
I ended up logging this as a bug with Chrome.

https://bugs.chromium.org/p/chromium/issues/detail?id=1423408#c5
