### ISSUE TITLE
Opening links doesn't focus the browser window when the browers is on another desktop

### ISSUE THREAD

**Issue by matthewdias** [johnste/finicky#29]
When i open links in chrome through finicky, the browser window doesn't gain focus.

**Comment by johnste** [comment]
Hey Matthew.

Does this happen every time you open a link? If you're using finicky to open other apps, does it happen there as well?

Would you mind posting your configuration?

**Comment by matthewdias** [comment]
It happens 90% of the time, even with only the following as my config:

```
finicky.setDefaultBrowser('com.google.Chrome')
```

Further testing shows it only happens when the Chrome window is on another desktop. Doesn't seem to happen when opening in other apps.

**Comment by johnste** [comment]
OK, that makes the problem clearer. I don't tend to use multiple desktops, so that's probably why I haven't seen the bug.

I can't make any promises right now (busy with life most of the time right now), but at least I can I have a look soon to see if I can reproduce the issue.

**Comment by matthewdias** [comment]
awesome. if you get time to look at it, let me know if you need help debugging.

**Comment by johnste** [comment]
I'm not going to have access to a suitable development environment for the coming few weeks or maybe months, so I don't think I'll be able to help you out in a reasonable time. Sorry! :(

**Comment by matthewdias** [comment]
That's quite alright. I'll do some experimenting with the codebase myself to see if I can figure something out.

**Comment by johnste** [comment]
Please do! I saw someone who forked the repo to update the code to compile in Swift 2.2 in a more recent version of XCode, so maybe that can give you a head start. https://github.com/extropic-engine/finicky

**Comment by matthewdias** [comment]
Update: Seems to be a bug with Chrome. When you have a Chrome window on the same desktop as the sender app, but the _last focused_ chrome window is on another desktop, this process occurs:

- url is opened on the chrome window on the other desktop (the last focused one)
- that new desktop is switched to
- chrome's active window becomes the one on the same desktop as the sender app
- the active application in the OS is the sender app

I've tested it with Safari and other apps, and the issue is isolated to Chrome. I'll submit a bug report to the Chrome team.
