### ISSUE TITLE
ms edge multiple profile 

### ISSUE THREAD

**Issue by mariomare22** [johnste/finicky#306]
**Describe the bug**
I am trying to configure finicky to work with multiple profiles with ms Edge I checked and there are two profiles: Default and Profile 1.

<img width="600" alt="Screenshot 2023-05-22 at 13 13 15" src="https://github.com/johnste/finicky/assets/12135860/e632561c-cf28-428e-b875-0275b36e27e2">

```
2023-05-22 13:07:28 - Configuration: Error: unknown key profile at module.exports.handlers[0].profile
unknown key profile at module.exports.handlers[1].profile
unknown key profile at module.exports.handlers[2].profile
unknown key profile at module.exports.handlers[3].profile
unknown key profile at module.exports.handlers[4].profile
unknown key profile at module.exports.handlers[5].profile
```

**Your configuration**
Please add a link to or paste the relevant parts of your configuration here

```
module.exports = {
  defaultBrowser: "/Applications/Microsoft Edge.app",
  handlers: [
    {
      // Open any url including the string "workplace" in Edge
      match: /microsoft.com/,
      browser: "/Applications/Microsoft Edge.app",
      profile: "Default", 
    },
 .........
 ```

**To Reproduce**
1. Change config
2. Reload
3. See error

**Comment by azhuchkov** [comment]
It's a configuration problem. It should be written as:
```
browser: { 
    name: "Google Chrome",
    profile: "Default", 
}
```
I.e. `profile` must be added to the `browser` object, not as its sibling.

**Comment by mariomare22** [comment]
Thanks that did the trick!
