### ISSUE TITLE
Howto open Torbrowser?

### ISSUE THREAD

**Issue by notDavid** [johnste/finicky#31]
What's the correct `BundleIdentifier` belonging to the TorBrowser app? i can't seem to find it...

- and is there an easy command to find a BundleIdentifier belonging to any X.app ?

Thank you.

**Comment by notDavid** [comment]
ahhh found it... - it has a space in it :o

```
$ mdls -raw -name kMDItemCFBundleIdentifier /Applications/TorBrowser.app
org.mozilla.tor browser
```

**Comment by johnste** [comment]
I'm glad you found the solution. Thanks for sharing!
