### ISSUE TITLE
Slack does not work as a Source Application

### ISSUE THREAD

**Issue by rdimartino** [johnste/finicky#32]
I'm using Finicky v0.5. I ran `osascript -e 'id of app "Slack"'` to get the bundler ID for Slack:
`com.tinyspeck.slackmacgap`. And I have the following in my config file:
```
finicky.onUrl(function(url, opts) {
	var sourceApplication = opts && opts.sourceBundleIdentifier
	if (sourceApplication === 'com.tinyspeck.slackmacgap') {
		return {
			bundleIdentifier: 'com.google.Chrome'
		}
	}
});
```
But links still open in my default browser. Other configuration rules work for links that are opened from Slack, e.g., 'Open Spotify links in client' from the example configuration.

**Comment by johnste** [comment]
Hi Robert!

The `finicky` api has a logging method `log(string)`, so I took a look at the bundle identifier reported by Slack and it is `com.tinyspeck.slackmacgap.helper`. 

I'll add a note of this. Thanks for using finicky!

**Comment by johnste** [comment]
Of course, let me know if it's still not working for you!

**Comment by rdimartino** [comment]
Great! That works! Thanks!
