### ISSUE TITLE
Document log()

### ISSUE THREAD

**Issue by stackptr** [johnste/finicky#33]
I saw it referenced here: https://github.com/johnste/finicky/issues/32#issuecomment-311896626

However, I can't see any documentation and I'm not really sure where the logging goes (a file? a debugger pane?). Would be really useful in working through problems with the config file.

**Comment by johnste** [comment]
Hey Corey, good point! I also had a few issues finding where the logs ended up. :)

They end up in the system log, located at `/private/var/log/system.log`, so you can just tail the log `tail -f /private/var/log/system.log | grep finicky`. 

You can also see the logs  in the Console app, see:
 ![screenshot](http://imgur.com/JC744xu.png) 

I'll make a note of it in the documention. Thanks for the suggestion.

**Comment by johnste** [comment]
I added a note on `log` in the documentation [here](https://github.com/johnste/finicky/wiki/Javascript-API-Documentation)

Let me know if you have more questions or suggestions. Thanks for using finicky!

**Comment by stackptr** [comment]
Does logging still work? finicky seems to not be routing any links lately, I added a `log` and reloaded the config but I can't see it in my `system.log`

I am running Sierra 10.13.2 Beta (17C67b) so if this isn't broken for anyone else I'll accept the cost of running beta software ;)

**Comment by johnste** [comment]
I just upgraded to 10.13.1, and Finicky is routing and logging just fine for me.  I'm not planning on trying the Beta so it'll be hard for me to troubleshoot this.

**Comment by stackptr** [comment]
Argh, took another look this morning and found I wasn't using `finicky.log()` but rather just `log()`--the note I made in my config file was misleading. Everything seems to be working fine on the betas!
