### ISSUE TITLE
Config not loaded?

### ISSUE THREAD

**Issue by gitetsu** [johnste/finicky#35]
Hi. I installed Finicky from homebrew-cask and wrote my config file below, but every links opened in Google Chrome.

```Shell
$ cat ~/.finicky.js
finicky.setDefaultBrowser('com.vivaldi.Vivaldi');

finicky.onUrl(function(url, opts) {
  if (url.match(/^https?:\/\/slack-redir\.net\/.+?google\.(com|co\.jp/))) {
    return {
      bundleIdentifier: "com.electron.brave"
    };
  }
});

finicky.log('test');
$ osascript -e 'id of app "Vivaldi"'
com.vivaldi.Vivaldi
$ osascript -e 'id of app "Brave"'
com.electron.brave
$ sw_vers -productVersion
10.13.4
```

And there is no output `test` in Console.app's system.log.
I found below displayed sometimes.
```
Finicky[18950]: BUG in libdispatch client: kevent[vnode] monitored resource vanished before the source cancel handler was invoked
```

When I rename my config file `~/.finicky.js.bak` and click a link,
```
com.apple.xpc.launchd[1] (net.kassett.Finicky.8416[19527]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0]
```

Could you tell me how can I fix this?
Do you have any thoughts about what the cause might be?

**Comment by johnste** [comment]
Hi!

If you comment out every thing but the call to `setDefaultBrowser`, does
Vivaldi start for all kinks?

I can have a closer look in a while.

**Comment by gitetsu** [comment]
Thank you for quick reply!
Oh, I never thought about that...

When Vivaldi is already started, the link opened in new tab.
When not, opened in new window.

**Comment by gitetsu** [comment]
Wow.. I'm very sorry for taking your time :bow:
It works fine!
And Thank you for your great work! This is very helpful.

**Comment by johnste** [comment]
No worries, glad to help!
