### ISSUE TITLE
Option to hide the menu bar icon

### ISSUE THREAD

**Issue by coremessage** [johnste/finicky#41]
It would be very nice if the icon could be hidden. It's not clear how to control the application without the icon, though, but maybe simple `ps aux` and `kill` will do...

**Comment by johnste** [comment]
Looking into this for the upcoming update. Will look into how to control finicky without it too.

**Comment by dkBrazz** [comment]
As it is configured very rarely and doesn't need to show any status good point is to put config into the "System Preferences"

**Comment by johnste** [comment]
I think it makes a lot of sense to add finicky as a preference panel, though I have a bunch of legwork to do to learn how to build those. 

I might end up releasing a new version without it first to support the new config format.

**Comment by johnste** [comment]
Next release contains config to hide the icon.

**Comment by johnste** [comment]
This is now supported in the Finicky 2 RC 0 release https://github.com/johnste/finicky/releases/tag/v2.0-rc.0

Checkout the `options.hideIcon` option
