### ISSUE TITLE
Support to add new or custom short URL providers

### ISSUE THREAD

**Issue by pqrth** [johnste/finicky#42]
There are a lot of short URL providers, so finicky can't keep a [list of all providers](https://github.com/johnste/finicky/blob/master/Finicky/Finicky/FNShortUrlResolver.swift#L30-L41). Hence, it would be really helpful if users are allowed to declare custom short URL providers in their finicky configs.

**Comment by johnste** [comment]
Great idea! I'll look into it.

**Comment by johnste** [comment]
Plan on adding this feature to the next release. New config format supports it.

**Comment by johnste** [comment]
This is now supported in the Finicky 2 RC 0 release https://github.com/johnste/finicky/releases/tag/v2.0-rc.0

Checkout the `options.urlShorteners` option
