### ISSUE TITLE
Support for showing a browser menu

### ISSUE THREAD

**Issue by advicepyro** [johnste/finicky#43]
Currently I have work and personal accounts mixed in my mail app (Spark). I have a regex rule for catching domains belonging to work-related sites, but there might be a few ambiguous cases - for example, if someone were to share a Google Docs link with me on my personal account, when most of the time I get links via my work Google Apps accounts.

Would be nice if I could pass in an array of bundle identifiers and I get a simple overlay with the app icons near my mouse pointer to choose the browser of my choice, something like Choosy's implementation.

**Comment by johnste** [comment]
Interesting idea! I'll definitely consider it for the next version I'm currently working on.

**Comment by garhbod** [comment]
https://will-stone.github.io/browserosaurus/

**Comment by johnste** [comment]
Won't make the next version, but maybe later

**Comment by notDavid** [comment]
Another idea might be to be able to configure a modifier key for this, so for example:
- if no key is pressed while opening an url, use Safari (default)
- if CMD is pressed while opening an url, open Firefox
- if OPTION is pressed while opening an url, open Tor Browser

that way, you won't have to deal with UI stuff/delays.

**Comment by johnste** [comment]
In the latest release (2.1.0) there is now support for modifier keys. https://github.com/johnste/finicky/releases/tag/v2.1.0

Still considering adding ui for selecting browsers, but won't happen soon without outside help.

**Comment by johnste** [comment]
This feature will not make it in Finicky any time soon, so I'm closing this issue. In the meantime, if you want a visual menu, I suggest you try [Browserosaurus](https://browserosaurus.com/).
