### ISSUE TITLE
Support for opening links in a browser on another machine

### ISSUE THREAD

**Issue by dbergey** [johnste/finicky#44]
I run two computers (personal and work) with a shared mouse and keyboard. I run Slack on one machine, and would like to open links matching work-related domains on the other machine.

Perhaps we could optionally return a hostname as well as a bundleIdentifier.

Equivalent AppleScript: `tell application "<browser>" of machine "eppc://hostname.local" to open location "https://apple.com"`

**Comment by johnste** [comment]
Wow, that's an interesting use case! I can really see how that would help.

Unfortunately, I will probably not be able to look into this in quite a while since I have a lot of other updates and features I will focus on before this. I'll keep it in mind though.
