### ISSUE TITLE
"Open in Active Browser" App (finicky lightweight)

### ISSUE THREAD

**Issue by MentalGear** [johnste/finicky#45]
First, thank you for this app - it's almost what I have been looking for for a long time!
As a web developer, I use many different browsers, and often times clicking a link, opens instead of the active browser the currently set default browser (sometimes started with 100s of tabs) which is super annoying.
It's great that I can set to open links with the most recent active browser (and the JS API is also nice), yet the setup with config files is a bit of a hassle and I think it could be more simple & elegant.

It would be great if you could make a lightweight version, where all it does is use the last active browser for links, and which is just a single simple app.

**Comment by johnste** [comment]
Interesting idea! I'm currently updating the app, including changing how the configuration file works, and the possibility of opening links in the the open might go away.

I'm open to the possibility of creating a second application that solves this problem though. As you say, it would be pretty different and a lot more light weight.

**Comment by MentalGear** [comment]
Yes, a lightweight app just for this would be awesome!
Been using finicky now for several weeks, however just exclusively for the "open in the most recent browser" feature.

**Comment by balupton** [comment]
The readme seems to indicate that this is possible but I can't find any explanation of how to accomplish it

**Comment by johnste** [comment]
The last example [here](https://github.com/johnste/finicky/blob/master/README.md#example-configuration) shows how you can return an array of browsers and have finicky open the link in the first one already open.

**Comment by heliostatic** [comment]
Ah! I was wondering what happened to this feature :/ Would love to see its return.

**Comment by johnste** [comment]
I'm working on it, but making 2.0 more stable is taking precedent over it
right now. Soon, hopefully. :)

**Comment by apaolino** [comment]
Hi, thanks for this great software. There any news on this issue? Would be super useful

**Comment by MentalGear** [comment]
Second that! A stand alone "open in last browser app" would be it!

**Comment by johnste** [comment]
i think it's a good idea, but I don't have any plans on building a separate app right now.

**Comment by apaolino** [comment]
I was thinking more at a simple option/handler inside existing app

Il Ven 10 Apr 2020, 18:50 John Sterling <notifications@github.com> ha
scritto:

**Comment by MentalGear** [comment]
Any updates ? :)

**Comment by FezVrasta** [comment]
Hi, what's the method to get the last used browser? I can't find it in the docs.
