### ISSUE TITLE
Finicky doesn't seem to work on mojave

### ISSUE THREAD

**Issue by matthewess** [johnste/finicky#46]
To start, I'm using macOS Mojave 10.14.3, 

I downloaded finicky from brew (`brew cask install finicky`), then added the following code to `~/.finicky.js`:
```javascript
finicky.setDefaultBrowser('org.mozilla.firefox');

// yelpy links in chrome
finicky.onUrl((url, opts) => {
  if (url.match(/^(https?:\/\/.*(yelp|yelpcorp)\.com/)|(https?:\/\/)?y/) {
    return { bundleIdentifier: 'com.google.Chrome' };
  }
});

// slack apps in slack
finicky.onUrl((url, opts) {
  if (url.match(/^https?:\/\/.*\.slack.com/) {
    return { bundleIdentifier 'com.tinyspeck.macgap' };
  }
});


finicky.onUrl(function(url, opts) {
  return {
    bundleIdentifier: [
      "org.mozilla.firefox",
      "com.google.Chrome"
    ]
  };
});
```

However, nothing seems to take effect. All links, as far as i cant tell, open in chrome, which was my default browser before finicky was set.

**Comment by johnste** [comment]
I'm using finicky on Mojave without any issues. There are a number of syntax errors in your Javascript. Try this version where I've fixed them:

```js
finicky.setDefaultBrowser("org.mozilla.firefox");

// yelpy links in chrome
finicky.onUrl((url, opts) => {
  if (url.match(/^(https?:\/\/.*(yelp|yelpcorp)\.com\/)|(https?:\/\/)?y/)) {
    return { bundleIdentifier: "com.google.Chrome" };
  }
});

// slack apps in slack
finicky.onUrl((url, opts) => {
  if (url.match(/^https?:\/\/.*\.slack.com/)) {
    return { bundleIdentifier: "com.tinyspeck.macgap" };
  }
});

finicky.onUrl(function(url, opts) {
  return {
    bundleIdentifier: ["org.mozilla.firefox", "com.google.Chrome"]
  };
});
```
In the upcoming release I've built in error messages in finicky where it will tell you if you have problems in the config.

**Comment by matthewess** [comment]
😅Thanks! I did a quick write up in Vim looking at the example script but I should have linted it first, sorry about that!

**Comment by johnste** [comment]
No worries, it just goes to show that having finicky tell you somethings wrong is better than silently failing. Thanks for using finicky, and feel free to give any feedback.
