### ISSUE TITLE
Valid config for v0.5 produces an error in v2.0-alpha

### ISSUE THREAD

**Issue by euf** [johnste/finicky#47]
My config file is following:

```js
finicky.setDefaultBrowser('com.apple.Safari');

finicky.onUrl(function(url, opts) {
  var sourceApplication = opts && opts.sourceBundleIdentifier;
  if (
    sourceApplication === "com.tinyspeck.slackmacgap" || 
    sourceApplication === "org.rstudio.RStudio" || 
    sourceApplication === "com.apple.mail") {
    return {
      bundleIdentifier: "com.google.Chrome"
    };
  }
});

```

When I run Finicky **Version 0.5 (1)** downloaded from [Releases](https://github.com/johnste/finicky/releases/tag/v0.5), it works as expected.

When I build and run **Version 2.0-alpha (1)** cloned from master (latest commit [5cb2ff1](https://github.com/johnste/finicky/commit/5cb2ff13e5098a7ad55eb7f02a5f1d4680c6e35e)), it gives me an error (see screenshot).

<img width="100%" alt="Finicky Version 2.0-alpha config error notification" src="https://user-images.githubusercontent.com/11754264/56852225-25c4c300-6921-11e9-8656-99c3fce51064.png">

How should I fix this error? The main reason for trying new version was expected "Hide menubar icon" feature (though I didn't find a way to activate it).

Btw, thanks for the great app! It improves one's workflow in a brilliant way.

**Comment by johnste** [comment]
Hi euf!

Wow, I never expected anyone to test stuff in the next version already. The API that the current release uses has changed quite a bit for the next release. I'm aiming for some sort of compatibility mode or guided assistance on how to convert the config, but I've yet to start developing that further.

For now, if you still want to try out the alpha, you can have a look at the example config[in the wiki](https://github.com/johnste/finicky/wiki/Finicky-2-Javascript-API-(WIP)). 

I do want to note that `sourceBundleIdentifier` is not yet supported in the alpha, so you config won't port perfectly.

Thanks for kind words, for trying the alpha, and for using finicky. I hope to have a bigger update soonish, but it's hard to make any guarantees with limited time to spend on its development.

**Comment by euf** [comment]
Thanks for your reply, johnste!

I wasn't aware that `sourceBundleIdentifier` is not yet supported in the alpha, and as you can see from my config it's a primary feature for me, so I'll stick to stable v0.5 for the moment then.

Let me give you a piece of advice: you may want to make a post at HackerNews and similar resources after releasing your bigger update and coming out from alpha. I find finicky extremely great and at the moment its popularity is undeservedly low. Many developers and regular users would like to choose browser automatically, and the app has no analogues, so one should spread the word ;)
