### ISSUE TITLE
Dialog for choosing between installed browsers 

### ISSUE THREAD

**Issue by johnste** [johnste/finicky#5]
Add a dialog that appears to be able to select what browser is to be launched

**Comment by Metamba** [comment]
Can this work within an app? For example, can I be redirected to a duckduckgo page when I try to use bing within Safari?

**Comment by johnste** [comment]
Yes - check out the example in the README file.

```javascript
// Always open links from Mail in Safari
finicky.onUrl(function(url, opts) {
    var sourceApplication = opts && opts.sourceBundleIdentifier
    if (sourceApplication === 'com.apple.mail') {
        return {
            bundleIdentifier: 'com.apple.safari'
        }
    }
});
```

 This issue seems unrelated to your question, though.

**Comment by johnste** [comment]
I've decided that, for now, I don't think this is an important feature to develop - you should always have a default browser set up to grab these.

**Comment by johnste** [comment]
Reconsidering this. A prompt with a list of installed browsers would be neat when no default browser is set.

**Comment by Metamba** [comment]
Hi,This is a great idea. Is it possible for your app to be coupled to another app like keyboard maestro. I am thinking of a macro that will grab magnet or torrent links and download directly to a seedbox. One can also redirect map links in a browser to the map apps of ones choice. An old app, Lincastor did some work in this direction but it is no longer actively supported.Thanks.
Doyin




On Sun, Aug 9, 2015 at 6:30 AM -0700, "John Sterling" <notifications@github.com> wrote:












Reconsidering this. A prompt with a list of installed browsers would be neat when no default browser is set.

**Comment by johnste** [comment]
Hey Metamba. Please create new issues for feature suggestions and questions that are unrelated to the issue at hand.

**Comment by lucasmotta** [comment]
Hey @johnste, I know this is an old issue, but I didn't want to create a new one just to ask if this feature has ever been implemented?

**Comment by johnste** [comment]
Hi @lucasmotta. I never ended up working on this, sadly. I don't think it is terribly likely I will work on it either for the foreseeable future.

**Comment by FezVrasta** [comment]
Is there any chance for this to be reconsidered? I'm moving from Choosy and I really miss the ability to decide case by case which browser profile to use for unhandled URLs.

**Comment by bric3** [comment]
I would prefer this in Finicky. But I ended up using https://github.com/will-stone/browserosaurus

So, when I know a link cannot be distinguished in Finicky and that I need to select the browser, I choose Browserosaurus in the handler.

E.g. in slack when I need to log in, or refresh the SAML token, I need to open the link in either my work browser or my personal browser. Unfortunately the URL looks like this `https://app.slack.com/ssb/add?s=1&v=<slack version>&ssb_vid=.<an hex id>&ssb_instance_id=<a uuid>`, and doesn't allow to make rules for either work or personal, so there I'm redirecting to Browserosaurus.


```javascript
// Get bundle id with: mdls /Applications/Firefox.app | grep kMDItemCF
const browsers = {
  personal: {
    name: 'org.mozilla.firefox', // or Firefox
    openInBackground: false,
  },
  work: {
    name: 'com.google.Chrome', // or Google Chrome
    // profile: 'Profile 1', // must match folders, e.g. ~/Library/Application\ Support/Google/Chrome/Profile\ 1
    openInBackground: false,
  },
  selector: {
    name: 'com.browserosaurus', // or Browserosaurus
    openInBackground: false,
  }
}

module.exports = {
  handlers = [
    ...,
    {
      // Select browser when slack wants to login
      // https://app.slack.com/ssb/add?s=1&v=4.41.90&ssb_vid=.<hex id>&ssb_instance_id=<UUID>
      match: [
        "app.slack.com/ssb/*"
      ],
      browser: browsers.selector,
    },
  ]
}
```

![image](https://github.com/user-attachments/assets/1e097866-5848-4cd1-9fdb-e1411e2ec0b2)
<img width="271" alt="image" src="https://github.com/user-attachments/assets/b85946a5-205f-4515-bcb0-0ab2570bd25b">
The only downside is that Browserosaurus do it hide _browser-like apps_ (Zoom, Spotify, etc) but you can drag them below.

Finicky remains my default browser.
![image](https://github.com/user-attachments/assets/b8cd144e-b2fd-45b9-ab32-89c465a5b0a2)
