### ISSUE TITLE
Configuration parsing fails inconsistently

### ISSUE THREAD

**Issue by stackptr** [johnste/finicky#53]
I'm migrating my [old config](https://github.com/stackptr/dotfiles/blob/94e7e55b9098e39fb042bfebc6bf8333c8be83e4/finicky.js) to the new format but am seeing a notification about an error parsing config. In order to try to isolate the problem, I copied the config from the "Advanced usage, settings" section of the README in order to start adding my old configuration bit by bit.

As expected, when I copy over everything intact to `.finicky.js` I see that a notification that the file was loaded, but if I save again (with no changes to the stock config) it appears to fail maybe half the time. Closing and reopening Finicky does not change this behavior.

This was seen on RC0 (in About: Version 2.0-RC0 (1)).

In RC1 which appears to have been uploaded as I was writing out this issue, I get some slightly better output, though it is still failing around half of the time:

```
2019-05-21 13:06:58 - Error parsing config: "TypeError: undefined is not an object (evaluating 'object[key]')"
```

Again, this is with the stock config:

```javascript
module.exports = {
  defaultBrowser: "Google Chrome",
  options: {
    // Hide the finicky icon from the top bar
    hideIcon: true
  },
  handlers: [
    {
      // Open any link clicked in Slack in Safari
      match: ({ sourceBundleIdentifier }) =>
        sourceBundleIdentifier === "com.tinyspeck.chatlyio",
      browser: "Safari"
    },
    {
      match: ["http://zombo.com"],
      browser: {
        name: "Google Chrome Canary",
        // Force opening the link in the background
        openInBackground: true
      }
    }
  ]
};
```

**Comment by stackptr** [comment]
Looks like RC1 has better parsing errors and the problem with my configuration port is that the updated API seems to no longer allow an array of browsers to specify fallback. That's unrelated to this issue, but I managed to get my port to load, just had to try a few times until the parser accepted it.

**Comment by johnste** [comment]
Ok, it sounds weird that it would sometimes not accept your config. The error itself comes from the schema validation where a value seems to be unset. I should be able to improve the error message.

Were you always getting the same error message? 

If possible, please post your current config here so I can test it.

I'm considering adding the array of browsers back as an option but I wasn't sure if people were using it enough.

**Comment by stackptr** [comment]
My config is now checked in in my dot files repo, [here](https://github.com/stackptr/dotfiles/blob/master/finicky.js) (the link in the issue has been updated to reflect the older file I was migrating over).

It's always the same error message:

<img width="703" alt="Screen Shot 2019-05-21 at 1 34 42 PM" src="https://user-images.githubusercontent.com/4542907/58128760-3806e980-7bcd-11e9-9dd0-fb02fc18c122.png">

**Comment by johnste** [comment]
Thanks you! 

Your updated configuration works just fine for me which feels incredibly weird. I'll try it some more to see if I can figure out what's going on.

I want to note your config won't fully work. `finicky.matchDomains()` is a function that will only match against domains and your array `workUrls` contain full urls regular expressions. You can use the `workUrls` array directly instead:
```js
// Freckle-related links in work browser
const workUrlsHandler = {
  match: workUrls,
  browser: workBrowser
};
```

**Comment by johnste** [comment]
I'm updating the validation library to create better error message, so for the next RC troubleshooting should be slightly easier.

**Comment by johnste** [comment]
I might have found a bug related to how finicky listen for changes/reloads the configuration. 

It might be related to starting finicky without any configuration file in place and then creating it while finicky is running. I'll try to investigate further later today.

**Comment by johnste** [comment]
@stackptr Are you still seeing issues related/similar to this? Trying to figure out if this is mainly seen during on-boarding or if it's an ongoing issue.

**Comment by johnste** [comment]
Just released a new RC that hopefully fixes this issue. If you encounter something similar please comment on this issue.

**Comment by llange** [comment]
Hi, I believe I'm facing the same issue - with v2.1.0 (136)
Whatever the config file (even an empty `handlers:`), I have a validation error - not during reload time, but at the first use (or with the 'Finicky Console').
The error I have is not easy to understand:
```
2019-07-02 15:53:09 - Configuration: TypeError: undefined is not an object

2019-07-02 15:53:09 - Configuration: SyntaxError: Unexpected token '...'. Expected a property name.
```
I believe this could be unrelated to the config file (because I remove every last bit of it), and thus it may be related to other parameters.
My config:
```
MacBookPro13,3
ProductVersion:	10.12.6
BuildVersion:	16G2016
```
Could it be related to a dependency on an external library / component / ... ?

**Comment by johnste** [comment]
@llange Can you post your config on gist? https://gist.github.com   I should be able to help.

**Comment by llange** [comment]
Hi @johnste , thanks for the reply, you'll be disappointed with the config.
I removed all the bits, just enough that it continues to be parsed ok at the beginning and appears to be able to work - even this very config with no handlers fails:
```
module.exports = {
    defaultBrowser: {
        name: 'org.mozilla.firefox-perso',
        appType: 'bundleId',
        openInBackground: false
    }
}
```

I also tried this one with a "debug" handler, with the same result. There may be an error with this one but I did not catch it:
```
module.exports = {
    defaultBrowser: {
        name: 'org.mozilla.firefox-perso',
        appType: 'bundleId',
        openInBackground: false
    },
    handlers: [{
        match: (all) => {
            finicky.log(all);
        },
        browser: {
            name: 'org.mozilla.firefox-perso',
            appType: 'bundleId'
        }
    }]
}
```

That's why I think it's not coming from the config file.

What do you think about the bit with the syntax error that appears in the logs:
```
2019-07-02 15:53:09 - Configuration: SyntaxError: Unexpected token '...'. Expected a property name.
```
?

**Comment by johnste** [comment]
That is indeed disappointing. The configuration works fine for me. 😟 
I assume you tried restarting finicky. 

I wish I could look more into what config finicky thinks is currently active. If you try adding this line to the end of your config, what output can you see in the log window?
```
finicky.log(JSON.stringify(module.exports, null, 2))
```

**Comment by llange** [comment]
It logs the following:
```
2019-07-03 13:07:47 - {
  "defaultBrowser": {
    "name": "org.mozilla.firefox-perso",
    "appType": "bundleId",
    "openInBackground": false
  }
}
```

Any click or Finicky Console test result in the same error:
```
2019-07-03 13:08:02 - Configuration: TypeError: undefined is not an object

2019-07-03 13:08:02 - Configuration: SyntaxError: Unexpected token '...'. Expected a property name.
```
If I log on stdout, I have a little more info but still not usable:
```
Start listening to file changes
Cancel fileDescriptor
Reload config. showSuccess: false
Created new context
2019-07-03 13:55:29.340 Finicky[67972:868412] {
  "defaultBrowser": {
    "name": "org.mozilla.firefox-perso",
    "appType": "bundleId",
    "openInBackground": false
  }
}
Valid config: true
Error parsing config: "SyntaxError: Unexpected token '...'. Expected a property name."
Stack: undefined:73:undefined
Error parsing config: "TypeError: undefined is not an object"
Stack: undefined:undefined:undefined
```
(I don't know what the 73 is about, I have no line 73 nor column 73 in the file)

Additional information : I install the application with HomeBrew, in my local user "Applications" folder (~/Applications).

Here is the libraries and their versions as resolved on my system:
```
Šnek:~ llange$ otool -L ~/Applications/Finicky.app/Contents/MacOS/Finicky
/Users/llange/Applications/Finicky.app/Contents/MacOS/Finicky:
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore (compatibility version 1.0.0, current version 607.1.40)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1570.15.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1671.40.118)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1570.15.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 944.3.0)
	@rpath/libswiftAppKit.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftCore.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftCoreData.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftCoreGraphics.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftCoreImage.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftDarwin.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftDispatch.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftFoundation.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftIOKit.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftMetal.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftQuartzCore.dylib (compatibility version 1.0.0, current version 1001.0.82)
	@rpath/libswiftXPC.dylib (compatibility version 1.0.0, current version 1001.0.82)
```

**Comment by llange** [comment]
Note that I managed to make it work - and it confirms my hypothesis of a difference in external libraries version:

1.  I downloaded a recent webkit version from https://webkit.org/build-archives/ (I took the latest for Sierra - build 239857)
1. I updated the application to use this version instead of the system one (Note: I embedded the framework in the app itself but it was just because I was fiddling with it):
`install_name_tool -change /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore /Users/llange/Applications/Finicky.app/Contents/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore ~/Applications/Finicky.app/Contents/MacOS/Finicky`
(I believe I could use there a relative marker for the path - did not try it yet)
1. Then I opened the application (on command line), which was quite ok but 2 warnings (due to the recent webkit I believe):
```
2019-07-03 14:08:52.675 Finicky[78866:955766] NSSoftLinking - The DataDetectors framework's library couldn't be loaded from /System/Library/PrivateFrameworks/DataDetectors.framework/Versions/A/DataDetectors.
2019-07-03 14:08:52.675 Finicky[78866:955766] NSSoftLinking - The function 'DDMenuItemGetActionUTI' can't be found in the DataDetectors framework.
```

And I was able to open a link n the console:
```
2019-07-03 14:08:55 - Would open bundleIdorg.mozilla.firefox-perso  URL: https://example.com
```


So I believe it's due to my aging version of macos, itself having an old version of webkit.

I see multiple paths here
* Ignore old macos versions :-(
* Embed webkit JavaScriptCore.framework (additional 21M, need to know which version, depends on the OS version, ...)
* Find the functions that were modified and detect / find a workaround
* others ?

If some other have this issue (mainly @stackptr ), could they confirm their macos version / JavaScriptCore version to see if there is a pattern here ?

**Comment by johnste** [comment]
Thank you for your perseverance! 🙌 Lots of good info here. I'm running macOS `10.14.5`. What macOS version are you on? I'm not sure which version Finicky actually works with. 

Supporting older macOS version seems like it would be a lot of extra work. I could change the internal scripts that are failing, though that might be confusing when the examples use more up to date javascript syntaxes.

**Comment by llange** [comment]
Regarding the macos version, it's `10.12.6` - macos Sierra (Cf https://github.com/johnste/finicky/issues/53#issuecomment-507688982 for more infos)
Could you please run "otool -L ...." on your application, and give me the version of `JavaScriptCore.framework`installed on your system ? It's in the first lines of output.

Do you know which part is failing, and why ? It looks that some different behaviour occurs between my old `JavaScriptCore.framework` and the current one.

If so, I'd recommend against have different scripts (If you mean by that runtime-scripts, not build-time scripts) per macos version as it would make support a nigthmare.
However, having a different build (with specific rules that could, for example, bundle the `JavaScriptCore.framework` with the same version as yours for older macos'es) and producing multiple (2) binaries could be an idea.

I don't know XCode / xcodebuild but I believe this may be done.

**Comment by johnste** [comment]
otool gives me `/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore (compatibility version 1.0.0, current version 607.1.40)`

**Comment by johnste** [comment]
I'm using some newer javascript syntax which is what's causing most of the problems I think, like the spread operator and object destructuring. They are not that hard to backport but would make it slightly more cumbersome to work with.

Keeping multiple versions or binaries updated feels very cumbersome, instead I will consider bundling the javascript to only use older syntax, and post a warning about not supporting newer javascript syntax in the readme.

I have to assume there are good reasons to keep running older macOS versions?

**Comment by llange** [comment]
So what's strange here is that it's reported the same exact version as mine on the system, and also the one that I downloaded.
This `otool -L ...' command is no enough to determine what's different between those frameworks.

Regarding older macos version : I don't believe there are good reasons (for me) - just laziness. At some point I'll be forced to upgrade, but always managed not to do it yet.
