### ISSUE TITLE
Finicky crashes if started by clicking a url

### ISSUE THREAD

**Issue by johnste** [johnste/finicky#55]
Probably needs to wait for the config to be parsed before resolving urls

**Comment by bverkron** [comment]
I seem to be experiencing this too.  Originally I was getting the macOS crash dialog (report a problem, etc) now I get nothing.

**Comment by johnste** [comment]
[New release to fix this issue](https://github.com/johnste/finicky/releases/tag/v2.0-rc.2) _still working on other issues_
