### ISSUE TITLE
SyntaxError: Unexpected EOF even with example config

### ISSUE THREAD

**Issue by bverkron** [johnste/finicky#56]
Every time Finicky rc.1 loads or I reload the config I get the following. Even with the sample config.

`2019-05-24 13:46:41 - Error parsing config: "SyntaxError: Unexpected EOF"`

I have tried the ReadMe [Basic config](https://github.com/johnste/finicky#basic-configuration), [Wiki config](https://johnste.github.io/finicky-docs/interfaces/_finickyconfig_.finickyconfig.html), and console example config (below). All give the same error. Each time I copied and pasted into a editor like BBEdit or VS Code so there shouldn't be any formatting issues, at least not from the editors themselves.

```
   module.exports = {
        defaultBrowser: "Safari",
        handlers: [
            {
                match: finicky.matchDomains(["youtube.com", "facebook.com", "twitter.com", "linkedin.com"]),
                browser: "Google Chrome"
            }
        ]
    };
```

**Comment by bverkron** [comment]
I would like to just use the .5 version but seems the readme and doc have been updated to the new config examples. Do the old config samples still exist somewhere so I can get it operational in the meantime?

**Comment by johnste** [comment]
You can read the old samples / readme here for the .5 version: https://github.com/johnste/finicky/blob/b87ddc4ced565b40047361089ca4ea9618dce167/README.md

Thanks for posting an issue, I'm not sure what's going wrong yet but I'll try to have a look son!

**Comment by bverkron** [comment]
TY

**Comment by johnste** [comment]
I added a link to the docs in the 0.5 release

**Comment by johnste** [comment]
This sounds very similar to #53 where the contents of the configuration file doesn't seem to update correctly, so I'm going to track this issue there.

**Comment by bverkron** [comment]
Thanks. I thought it could be too but didn't see the specific message from this issue in #53 and couldn't get a good enough sense if it was related so decided to create a new issue instead of highjacking / muddying that one.
