### ISSUE TITLE
Feature Request: Reintroduce "Open in preferred running browser"

### ISSUE THREAD

**Issue by heliostatic** [johnste/finicky#57]
Would love to see renewed support for:

```
finicky.onUrl(function(url, opts) {
  return {
    bundleIdentifier: [
      "com.apple.Safari",
      "org.mozilla.firefox",
      "com.google.Chrome"
    ]
  };
});
```

**Comment by johnste** [comment]
Working on this now ⚡️

**Comment by johnste** [comment]
Latest release contains this feature. Still tagged as prerelease since some documentation is missing and need to run it a while for stability.

https://github.com/johnste/finicky/releases/tag/v2.2.0

**Comment by johnste** [comment]
Release fully in https://github.com/johnste/finicky/releases/tag/v2.2.1
