### ISSUE TITLE
sourceBundleIdentifier not working for Bitwarden

### ISSUE THREAD

**Issue by alexlec** [johnste/finicky#58]
Hello,

I'm using *sourceBundleIdentifier* for multiples sources check.
It's working nice for Slack (your example) or Skype.

```javascript
    {
      match: ({ sourceBundleIdentifier }) =>
        sourceBundleIdentifier === "com.tinyspeck.slackmacgap",
      browser: "Google Chrome"
    },
    {
      match: ({ sourceBundleIdentifier }) =>
        sourceBundleIdentifier === "com.skype.skype",
      browser: "Google Chrome"
    }   
```

I use the same for Bitwarden app :

```javascript
    {
      match: ({ sourceBundleIdentifier }) =>
        sourceBundleIdentifier === "com.bitwarden.desktop",
      browser: "Safari"
    }
```

I have taken the *Identifier* from the app :

```
cat /Applications/Bitwarden.app/Contents/Info.plist
...
    <string>com.bitwarden.desktop</string>
```
And it's never working, I always have theses links opened in the *defaultBrowser*

Can you please have a look ?

Thanks,

**Comment by johnste** [comment]
In your match function, try logging out the bundle identifier like so:

```
handlers: [ {
	match: ({ sourceBundleIdentifier }) => {
		finicky.notify(sourceBundleIdentifier);
		finicky.log(sourceBundleIdentifier);
	},
	browser: "Google Chrome",
}]
```

You should see a notification message with the bundle id (and a message in the finicky console).

**Comment by alexlec** [comment]
Many thanks @johnste 

That's the good (missing) tips (is it not a good idea to add this in help/faq ?)
I have found immediately the right *Identifier* with that : com.bitwarden.desktop.helper

And now, working nice.

Big thanks for your app !
