### ISSUE TITLE
Feature Request: Reintroduce support for modifier keys

### ISSUE THREAD

**Issue by michalmo** [johnste/finicky#61]
In version 0.5 i had my rules set up such that holding down the option key would open the url in my non-default browser. I used this in cases where I came across a link which I needed to open in the non-default browser right now, before updating my configuration later.

I'm sure there are people with more use cases one example in the current open issues is: https://github.com/johnste/finicky/issues/43#issuecomment-490792658

**Comment by johnste** [comment]
I created a release with keyboard support for you :) 
https://github.com/johnste/finicky/releases/tag/v2.1.0  🎉
