### ISSUE TITLE
how to chain rewrites and handlers?

### ISSUE THREAD

**Issue by gregschroeder** [johnste/finicky#63]
Prior to 2.0, I would rewrite all Slack URLs (which go through slack-redir, and have the URL as an argument), and then that cleaned up URL would be correctly processed by the Finicky handlers.  This worked great.

I cannot figure out how to get this to work in 2.0.  In isolation, things work.  The rewrite works (slack-redir URLs properly rewritten), and the handlers work (URLs are sent to correct apps), but I cannot seem to get them to work together (have a slack URL that I then want sent to a particular app).  What I want is, after the Slack redirect is unraveled, to then have the proper handler apply to that rewritten URL.

This would potentially be true for all of the other rewrite examples, such as forcing https but also handle URLs via different apps.

How can I do this?

**Comment by johnste** [comment]
Hey!

This should be working in the current app if I understand your setup correctly. The flow is something like this:

1. Rewrites are resolved in order. As the url gets rewritten it is sent on to the next rewrite.
2. The first handler that is a match on the updated url is triggered.

Maybe there's a bug. I'll try to recreate the problem. If possible, please post your config (or relevant parts) and I can check.


rewrites are handled first

**Comment by gregschroeder** [comment]
Great, maybe it's a simple thing I'm doing wrong, then.

https://gist.github.com/gregschroeder/e91a9b6c8b4dd940438bbe80408eae5a

**Comment by johnste** [comment]
I'll try to have a look sometime tonight. 

I'm curious, when does slack add slack-redir to their urls? I haven't noticed it at all when using the slack desktop app.

**Comment by gregschroeder** [comment]
I hadn't noticed it until attempting to grab and redirect Slack links, either. I run Slack in Franz, which runs their webapp.  If you right-click and do "Copy Link", Slack removes the redirect, but if you capture it when clicking on it, it is there.

example: https://slack-redir.net/link?url=https%3A%2F%2Fwww.npmjs.com%2Fpackage%2Fserverless-dynamodb-local whereas Copy Link gets https://www.npmjs.com/package/serverless-dynamodb-local

**Comment by johnste** [comment]
I see an issue with your configuration, but I'm not entirely sure it's the same one you have.
In your config, the regex matches the protocol including the colon like this: `http:` or `https:` . Finicky expects the protocol to not contain the colon, and fails to create a proper url. I verified this by adding a matcher that logged out the url like so:
```js
    {
      // Log all urls
      match(all) {
        finicky.log(JSON.stringify(all, null, 2));
        return false;
      },
      browser: "Safari"
    },
```

I changed the regular expression line to this:
```js
const match = redirectedUrlStr.match(/^(https?)\:\/\/(([^:\/?#]*)(?:\:([0-9]+))?)([\/]{0,1}[^?#]*)(\?[^#]*|)(#.*|)$/);
```

and now it seems to work.

Finicky should warn about this happening.

**Comment by johnste** [comment]
I also believe you can simplify your redirect rewrite function to this:

```js
    {
      // handle Slack redirects
      match: ({urlString}) => urlString.startsWith("https://slack-redir.net/link?url="),
      url: ({urlString}) => decodeURIComponent(urlString.substring("https://slack-redir.net/link?url=".length))
    },
```

`encodeURIComponent` and `decodeURIComponent` are built in functions to encode and decode url entities. Finicky accepts returning a url object or a string.

**Comment by gregschroeder** [comment]
great, thanks!  I was in a hurry because it was suddenly broken (I think I had done a brew update for something else), so I quickly hurried to convert 1.x syntax to 2.x.  For 1.x, I hadn't parsed the URL into component pieces - just a string replace, but thought the new syntax required a URL object.  So I grabbed a regexp from the interwebs, plugged it in, and was off by a colon in the protocol.  :)

This seems to work great:

```
 rewrite: [
    {
      // handle Slack redirects
      match: /slack-redir\.net/,
      url: ({urlString}) => decodeURIComponent(urlString.replace(/^.*slack-redir.net.*url=http/, 'http')),
    },
  ],
```

Thanks again for your help and efforts.  Finicky + epichrome is a great combination.

**Comment by johnste** [comment]
Oh, I didn't know someone updated brew cask to point to the new version.
