### ISSUE TITLE
wildcard match on match domains 

### ISSUE THREAD

**Issue by mergefailure** [johnste/finicky#69]
Hi there, 

I'm pretty new to swift, stilll trying to get my head around the syntax so can't quite tell if this is possible or how to go about implementing.

Is it posssible, when using finicky.matchDomains to somehow match on the base domain, for example :  

* google.com -> Chrome
* foo.google.com -> Chrome 
* bar.google.com -> Chrome

Is this possible, or something you would be interested in implementing.

I'd think something like the syntax of umatrix / ublock origin would be nice here, image shows how they do it.

<img width="1261" alt="Screenshot 2019-08-10 at 12 30 23" src="https://user-images.githubusercontent.com/53652064/62821322-d0788e80-bb6a-11e9-8e3a-81f2a5e1ac9e.png">

**Comment by johnste** [comment]
Hello!

`finicky.matchDomains` accepts an array with strings or regular expressions, so you could match your domains like so:

```
finicky.matchDomains([
   "google.com",     // match google.com domain as string (to make the regular expression less complicated)
   /.*\.google.com$/ // match all google.com subdomains
])`

I hope that works out for you. :)

**Comment by johnste** [comment]
As a side note, matchDomains is implemented in TypeScript [here](https://github.com/johnste/finicky/blob/d4bcbaea8d5026826d5e378bb328dc1a540700c1/config-api/src/createAPI.ts#L58)

**Comment by mergefailure** [comment]
perfect !
