### ISSUE TITLE
Feature reques: URL rewrite for handlers

### ISSUE THREAD

**Issue by exalted** [johnste/finicky#75]
As far as I understand URL rewrite functions ought to be defined in…

```
module.exports = {
  rewrite: [ /* Here */ ]
};
```

Although this is useful, I think, it would be even better if we could define those also in…

```
module.exports = {
  handlers: [
    {
      rewrite: [ /* Here */ ]
    }
  ]
};
```

That is _after_ an handler matches, but **before** it opens the URL in the defined browser.

This is useful, IMO, because at that point you wouldn't need to match the URL twice, and you could match based on given URL, but rewrite it before opening in the app.

What do you think?

**Comment by johnste** [comment]
It's a good idea, but I'm afraid it will make the configuration harder to understand. Might happen if there is enough support for it but not now.
