### ISSUE TITLE
Logs out of order

### ISSUE THREAD

**Issue by exalted** [johnste/finicky#76]
If you put multiple `finicky.log(…)` statements in a function, they will print in console from last to first, yielding an unexpected behavior.

Not a major issue, but confused me for a good 10 minute! 🙂

Try it!

```
finicky.log('A')
finicky.log('B')
finicky.log('C')
```

… will output

```
C
B
A
```

🙂 

Also, not strictly related, but while at it: `finicky.log('foo', 'bar')` won't work as one might expect similar to `console.log('foo', 'bar')`. Finicky will only take the 1st argument into consideration and ignore the rest.

**Comment by johnste** [comment]
This happens because finicky outputs all the logs in reverse chronological order – the most recent log statement will be the top one. If this is confusing to people I might consider changing it. :)

I see how multiple arguments to `finicky.log` could be useful, especially for experience JavaScript developers having those expectations on a log function.

**Comment by exalted** [comment]
Yeah well, no hard feelings here really. I like your work, so wanted to share my :two-cents:. I think it makes sense to output to console UI in reverse order, so the last output stays on top, however `console.log`-like statements should still behave as expected.

So, some pseudo-runtime code like:

```
app.output('A');
app.output('B');
finicky.log('X');
app.output('C');
finicky.log('Y');
finicky.log('Z');
app.output('D');
```

… should output:

```
D
Y
Z
C
X
B
A
```

… IMO. ✌️ 

---

`finicky.log` VS `console.log` is not a deal breaker, it's just surprising as I was kinda expecting it to be 1–1 binding.

**Comment by exalted** [comment]
Okay, let me try to break it down:

### Rules:

1. Entire thing above is executed top–bottom.
2. Consecutive `app.output()`s are printed in reverse chronological order (current behavior).
3. Consecutive `finicky.log()`s are printed in chronological order (opposite of the current behavior).

### Step 1:

```
==> app.output('A');
app.output('B');
finicky.log('X');
app.output('C');
finicky.log('Y');
finicky.log('Z');
app.output('D');
```

Output:

```
A
```

### Step 2:

```
app.output('A');
==> app.output('B');
finicky.log('X');
app.output('C');
finicky.log('Y');
finicky.log('Z');
app.output('D');
```

Output:

```
B
A
```

### Step 3:

```
app.output('A');
app.output('B');
==> finicky.log('X');
app.output('C');
finicky.log('Y');
finicky.log('Z');
app.output('D');
```

Output:

```
(X) // may not be outputted yet, because there may be consecutive `finicky.log()` calls
B
A
```

### Step 4:

```
app.output('A');
app.output('B');
finicky.log('X');
==> app.output('C');
finicky.log('Y');
finicky.log('Z');
app.output('D');
```

Output:

```
C
X
B
A
```

### Step 5:

```
app.output('A');
app.output('B');
finicky.log('X');
app.output('C');
==> finicky.log('Y');
finicky.log('Z');
app.output('D');
```

Output:

```
(Y) // may not be outputted yet, because there may be consecutive `finicky.log()` calls
C
X
B
A
```

### Step 6:

```
app.output('A');
app.output('B');
finicky.log('X');
app.output('C');
finicky.log('Y');
==> finicky.log('Z');
app.output('D');
```

Output:

```
(Y) // may not be outputted yet, because there may be consecutive `finicky.log()` calls
(Z) // may not be outputted yet, because there may be consecutive `finicky.log()` calls
C
X
B
A
```

### Step 7:

```
app.output('A');
app.output('B');
finicky.log('X');
app.output('C');
finicky.log('Y');
finicky.log('Z');
==> app.output('D');
```

Output:

```
D
Y
Z
C
X
B
A
```

**Comment by exalted** [comment]
Essentially `finicky.log()` calls are _stacked_ in memory —and not yet printed-out— until a `app.output()` call, or the program exists.

**Comment by johnste** [comment]
Alright, I think I understand what you are suggesting. However, I think switching the chronological order in the log window would make it easier to understand without building this "stacked" log feature.

**Comment by johnste** [comment]
Changing the chronological order of console output in next release
