### ISSUE TITLE
Matching multiple apps

### ISSUE THREAD

**Issue by smithjw** [johnste/finicky#77]
Can I confirm if this is the correct format for matching links from an array of apps in Finicky?

```
{
    // Open any link clicked in work apps in Chrome
    match: ({ sourceBundleIdentifier }) =>
    sourceBundleIdentifier = (["com.microsoft.Outlook","com.microsoft.teams"]),
    browser: "Google Chrome"
}
```

**Comment by johnste** [comment]
Hey James, you are almost there. I took the liberty of updating your code. This version should   hopefully work.

```
{
    // Open any link clicked in work apps in Chrome
    match: ({ sourceBundleIdentifier }) =>
     ["com.microsoft.Outlook","com.microsoft.teams"].includes(sourceBundleIdentifier),
    browser: "Google Chrome"
}
```

**Comment by smithjw** [comment]
@johnste I probably should have included that the config I used in my initial post does already work, just if it was the most correct way!

**Comment by johnste** [comment]
The code you posted had a few issues (assignment vs comparison and checking
if an item is included in an array) The version I posted should work just
fine though, and is the way I normally suggest to do it.

**Comment by smithjw** [comment]
>The code you posted had a few issues (assignment vs comparison and checking ...

@johnste ok great! I’ll update to your posted version as I simply tried a few different ways of making the array until it worked 😅

**Comment by tbrek** [comment]
@johnste 's solution does not work for me.

`{
      // Open any link in apps in Safari
      match: ({ sourceBundleIdentifier }) =>
        sourceBundleIdentifier = (["com.readdle.smartemail-Mac","com.apple.iChat"]),
      browser: "Safari"
    },
    {
      // Open any link in app using FF DE
      match: ({ sourceBundleIdentifier }) =>
        sourceBundleIdentifier = (["com.tinyspeck.slackmacgap","com.apple.Mail"]),
      browser: "Firefox Developer Edition"
    }`

When I click link in Slack it opens in Safari.

**Comment by johnste** [comment]
> @johnste 's solution does not work for me.

The first code example you posted isn't what I suggested though. I agree  `[].includes` is the way to go here.

**Comment by tbrek** [comment]
@johnste oh sorry. Tagged the wrong person. You me solution worked great.
