### ISSUE TITLE
Documentation doesn't mention that Finicky expands urls from url shorteners 

### ISSUE THREAD

**Issue by bartvdo** [johnste/finicky#79]
I've Little Snitch running and I was surprised to see that Finicky connected to an external source (t.co). Luckily because of it being open source I found out quickly why, because it does url shortening expansion to be able to direct those urls better.

Maybe say this in the documentation so it's not a surprise ?

(would do a pull request myself, but too busy at the moment and not that big a deal).

**Comment by johnste** [comment]
Thanks for telling me. It was mentioned before in the documentation but it was lost when I rewrote it. I'll add it.

**Comment by johnste** [comment]
I added a mention of it in [the readme](https://github.com/johnste/finicky/blame/master/README.md#L18)
