### ISSUE TITLE
Safari does not get focus if in another virtual desktop than where url is clicked

### ISSUE THREAD

**Issue by notDavid** [johnste/finicky#82]
1. Open Terminal app in 'Desktop 1'
2. Open Safari in 'Desktop 2'
3. Go to Terminal in Desktop 1 and execute `open https://github.com/`
4. Observe that Safari does not get focus (focus will stay on Desktop 1)

The same issue happens when clicking urls in Tweetbot (instead of Terminal.)

Finicky v2.2.2 (160)
macOS Catalina - 10.15 (19A602)

**Comment by johnste** [comment]
Published a new release that should fix this https://github.com/johnste/finicky/releases/tag/v2.2.3

**Comment by notDavid** [comment]
Can confirm it works 👍
