### ISSUE TITLE
Support URL Scheme

### ISSUE THREAD

**Issue by urapico** [johnste/finicky#86]
I'd like to use URL Scheme to open with specific desktop app.

ex) Trello mac app / https://apps.apple.com/jp/app/trello/id1278508951?mt=12

Now I rewrote protocol but I got an error message on finicky.

```js
    rewrite: [
        {
            match: finicky.matchHostnames(["trello.com"]),
            url: ({ url }) => ({
                ...url,
                protocol: "trello"
            })
        }
    ],
```

Error Message
```log
 Configuration: Error: url: Value not one of string or {
  "protocol": "https, http or file",
```

I suggest that the validation will be removed.

**Comment by stevemoser** [comment]
I was actually thinking of something similar. I want to open bookmarklets and javascript: protocol isn't recognized by the system open.
Also I wonder if I can inject some AppleScript into this app to open a bookmarklet like so:

`const bookmarklet_code="{query}"
const frontmost_app_name = Application('System Events').applicationProcesses.where({ frontmost: true }).name()[0]
const frontmost_app = Application(frontmost_app_name)
frontmost_app.doJavaScript(bookmarklet_code, { in: frontmost_app.documents[0] })
`

**Comment by johnste** [comment]
@urapico I can make this happen for sure. I hope to get some time this weekend to work on some open issues.

@stevemoser Not sure this can be done. I don't think `javascript:` is an actual valid url protocol? (I could be mistaken). 

As for AppleScript the alpha build for #49 is using it to control Chrome. Also I've seen requests for running AppleScript scripts so that's something I'm considering.

**Comment by johnste** [comment]
@urapico Published a new release that should fix this https://github.com/johnste/finicky/releases/tag/v2.2.3

**Comment by urapico** [comment]
It seems working fine.
Thank you very much. 👍

**Comment by blicksky** [comment]
> It seems working fine. Thank you very much. 👍

Hi @urapico, can you please post your configuration where you were able to have finicky open the Trello app? I can see the rewrite working in the finicky console, but I can't seem to get it to open the app.

**Comment by ralphjsmit** [comment]
@urapico Sorry for tagging you, but I'm trying to figure out how to set up Finicky for Trello. This issue was the only reference to Trello + Finicky that I could find 😄 Does the way you set it up still work and if so, could you share how you set up your configuration file?

My configuration file:
```js
module.exports = {
  defaultBrowser: "Safari",      
  rewrite: [
    {
      match: finicky.matchHostnames(["trello.com"]),
        url: ({ url }) => ({
          ...url,
          protocol: "trello"
        })
      }
  ],
  handlers: [
    {
      match: ["trello.com/*"],
      browser: "Trello"
    }
  ]
}
```
