### ISSUE TITLE
Is there an option to set manual choost, which browser to open?

### ISSUE THREAD

**Issue by skywinder** [johnste/finicky#92]
I found in readme only opening-preferred-browser (https://github.com/johnste/finicky#opening-preferred-browser)
But sometimes it would be good to manually choose, which browser to open.

**Comment by johnste** [comment]
That feature opens the first running browser in the supplied array. Maybe it needs a better name...

Unfortunately, no option to manually choose browsers from a list is available or planned right now.

**Comment by skywinder** [comment]
Good, thanks! 
probably it's enough just to mention it in readme, that is very good with exmaple, btw!
