### ISSUE TITLE
Specify browser by path (open url -a path)

### ISSUE THREAD

**Issue by ldub** [johnste/finicky#98]
Currently finicky opens browsers with a command like `open https://example.com -b com.google.Chrome`. Sometimes multiple browsers use the same bundle id (for example when using something like Epichrome to create multiple site-specific browsers). To support this, finicky needs to use a command like `open https://example.com -a /Applications/MyBrowser.app`.

https://github.com/johnste/finicky/blob/master/Finicky/Finicky/Browsers.swift#L16

**Comment by ldub** [comment]
I can try hacking on this myself but would like some input about:

1. whether you support this feature and would accept a PR
2. what the config should look like? I was thinking of overloading the appType config to accept `appName` `bundleId` or `appPath` like so:

    ```
    browser: {
        name: '/Applications/MyBrowser.app',
        appType: 'appPath'
    }
    ```
3. any tips you have for contributing/whether you encourage it

**Comment by johnste** [comment]
Will be available in the next release, thank you again @ldub
